### ISSUE TITLE
Entitlement - Ids in Confirmation message are not clear

### ISSUE THREAD

**Issue by hhaarsma** [stichtingsem/ecosystem#100]
In https://stichtingsem.stoplight.io/docs/ecosystem/4de627102aa52-accept-entitlement it is stated under the Response Body:
entitlementReferenceId - The ReferenceId that was part of the request should be echo's here
entitlementId -
entitlementReceiveId - 

And in https://stichtingsem.stoplight.io/docs/ecosystem/c2NoOjQ3OTkyNTQ0-entitlement-confirmation:
The entitlementReferenceId, entitlementId are echoed back to the MP, with a new entitlementReceiveId.

We implemented this as:
- EntitlementId = request.Entitlement.Id
- EntitlementReferenceId = request.EntitlementReferenceId
- EntitlementReceiveId = newly created internal reference Id

Is this the correct interpretation? Can we make the documentation more explicit to make this clear?

This also impacts the Usage event since there an entitlement Id is given back - which option should that be?

**Comment by kvoer** [comment]
Voorstel tot besluit: de implementatie zoals beschreven door Henk is correct.
Voorstel tot besluit: in het Usage event wordt de EntitlementId gebruikt. Niet één van de reference Ids. de reference Ids zijn er om het protocol van bevestigingsberichten te faciliteren.

**Comment by edwinverwoerd** [comment]
> Voorstel tot besluit: de implementatie zoals beschreven door Henk is correct. Voorstel tot besluit: in het Usage event wordt de EntitlementId gebruikt. Niet één van de reference Ids. de reference Ids zijn er om het protocol van bevestigingsberichten te faciliteren.

_AKKOORD_

**Comment by kvoer** [comment]
Solved in pull request #143
