### ISSUE TITLE
Should Get Consent be using api instead of referenceid?

### ISSUE THREAD

**Issue by hhaarsma** [stichtingsem/ecosystem#101]
For 'Request initial sync' we moved from referenceid to api because for a specific API, a specific school and a specific partner we expect only 1 Consent to be present, so the api indicator should be sufficient.
Isnt this also true for the Get Consent method?

**Comment by kvoer** [comment]
Overwegingen:

- De referenceId verwijst naar een uniek consent voor een school en een API. Alleen de API noemen is niet voldoende om een unieke consent terug te sturen.
- Dit hangt ook samen met issue #104 waarbij het schoolId soms in de Token zit en soms in de query/message.
- Er is nog een endpoint om alle consents voor een school op te vragen.
- De toepassing voor dit endpoint is mogelijk om de status van een specifieke consent te controleren. Op dat moment is de referenceId beschikbaar en identificeert deze de wederzijdse consent uniek.

Voorstel tot besluit:
Niet wijzigen

**Comment by edwinverwoerd** [comment]
Okay maar dan wel goed beschrijven in de afspraken set

**Comment by kvoer** [comment]
Dit issue is besproken in de werkgroep standaard van 30 november 2022:
- Het beoogde gebruik voor het endpoint is om te controleren op welke wijze de andere partij consent heeft geregistreerd voor de API en de School.
- Het voorstel is om daarom niet de referenceId als path parameter maar de school én de api als path parameter te hanteren. De response is in dat geval de registratie van het meest actuele consent.
- Indien een partij expliciet het consent wil opvragen voor een specifieke referenceId dan is het mogelijk om deze in een optionele query parameter mee te sturen.

In de review zouden we graag input ontvangen over:
- Gaan partijen informatie opvragen voor een specifiek referenceId?
- Zijn de referenceIds noodzakelijk in het Consent bericht of volstaat de actuele status van het consent?

**Comment by kvoer** [comment]
Review van It's Learning:

Wat mij betreft Digidelivery ID en de API(s) waarvoor consent wordt gegeven.
