### ISSUE TITLE
Inconsistency in api enum for Consents

### ISSUE THREAD

**Issue by hhaarsma** [stichtingsem/ecosystem#102]
In the request message for the Consent Update the following options are allowed:
catalogue-api
course-api
entitlement-api
usage-api
progress-api
sis-api

And in the response:
course-api
entitlement-api
usage-api
progress-api
sis-api

If catalogue-api can be requested, shouldnt it also be allowed in the response?  Or can it be removed?

**Comment by edwinverwoerd** [comment]
> Voorstel tot besluit: zowel course als catalogue verwijderen. Hier is geen consent van toepassing.

_AKKOORD_

**Comment by hhaarsma** [comment]
Dan zou ik opteren voor het alleen verwijderen van de Catalogue optie. 
In één van de meetings is er wel eens gesproken over school specifieke Products en Courses - Bij Products werd uiteindelijk toch geen goede use-case voor gevonden - maar bij Courses kan er gedacht worden aan door de school zelf ingerichte leerpaden. In dit laatste geval zal er dus wel consent nodig zijn om deze gegevens uit te kunnen wisselen.

**Comment by kvoer** [comment]
Zou je in het geval van custom Course en Catalogue informatie die je uitwisselt voor een enkele school of leverancier niet willen gaan voor een specifieke Scope die je hiervoor bilateraal afspreekt?

**Comment by hhaarsma** [comment]
ik zou zeggen dat Catalogue inderdaad een bilateraal verhaal is - dan heb je het in feite over producten die alleen aan 1 specifieke school verkocht worden.
Maar voor Course informatie zie ik nog wel het scenario dat een school zelf aan de uitgever kant de volgorde van content blokken kan veranderen, of sommige opdrachten expliciet niet wil laten doen - dit wordt dan in feite een school specifiek leerpad dat binnen de huidige afspraken al gecommuniceerd kan worden, alleen moet dat binnen de context van een specifieke school en dan ook met het consent van die school.
Door de Course optie in de opties te houden geef je partners de mogelijkheid om hier invulling aan te geven als zij dit nodig/wenselijk achten. Dan wordt het volgens mij een stukje administratie van kan die partner wel of niet school specifieke Course informatie leveren/ontvangen - net als er bijgehouden moet worden of een partner wel of niet iets met SIS informatie kan doen.

**Comment by kvoer** [comment]
In de werkgroep is het volgende besproken:
- De Catalogue en de Course API bevatten in de scope van het Ecosysteem de informatie die de LA wilt delen met de MP en het LMS.
- Er ontstaan ook varianten waarbij scholen specifieke Course structuren hebben. In de toekomst kan dit ertoe leiden dat Course informatie in de context van een enkele school uitgewisseld wordt. Dit is nu nog niet aan de orde.
- In verband met de scope voor deze fase (niet uitbreiden en vooral finaliseren) is deze aanpassing doorgeschoven naar later.

Voorstel tot besluit: Catalogue en Course weghalen.

**Comment by Jorimvdw** [comment]
Akkoord
