### ISSUE TITLE
On the Events API the event type sis.group is missing

### ISSUE THREAD

**Issue by hhaarsma** [stichtingsem/ecosystem#103]

**Comment by kvoer** [comment]
Voorstel tot besluit: toevoegen event type

**Comment by edwinverwoerd** [comment]
> Voorstel tot besluit: toevoegen event type

_AKKOORD_

**Comment by kvoer** [comment]
Zoals ook besproken in issue #24 gaan we voor een andere wijze van implementeren van Groups.

**Comment by kvoer** [comment]
#143
