### ISSUE TITLE
Unclear when to expect digideliveryid in the jwt token and when in the message

### ISSUE THREAD

**Issue by hhaarsma** [stichtingsem/ecosystem#104]
In general the token gives the context for which a request is done, so that contains the digideliveryid of the school - so the message can be treaded in the context of that school.
For some API methods the message also contains a digideliveryid:
- Entitlement - Post AcceptEntitlements
- SIS - event messages (via School object)
- Consent update

How do we ensure consistency here?

**Comment by kvoer** [comment]
Overwegingen:
- Consent kan worden gegeven op het niveau van een Bestuur of een School met meerdere vestigingen. Er wordt dan data uitgewisseld in de context van digiDelivery Id A. De bestellingen kunnen zijn gedaan voor scholen i, ii en iii.
- In de SIS API is de school_id geen query of path parameter voor het opvragen van informatie.
- Entitlements moeten ook verstuurd kunnen worden voor een particulier (Personal Entitlement). Hier is de school niet bekend. Hoe implementeren we dit?

Voorstel tot besluit:
- Via de Entitlement API en SIS API worden gegevens uitgewisseld voor een school. Hierbij gaat het om de entiteit School in relatie tot een bestelling (Entitlement API) en de Leerlingen, Schoolperioden, Schoolvakken, Leraren (SIS API).

**Comment by kvoer** [comment]
In aanvulling op deze discussie zag ik dat het school_id ook onderdeel is van ieder bericht. In hoeverre is dit noodzakelijk voor correcte werking?

**Comment by edwinverwoerd** [comment]
SchoolID op ieder event is noodzakelijk maar ook optioneel. Denk aan B2C acties. MBO! en ook steeds meer VO.
Voor deze versie stel ik voor dat we deze niet weghalen, zeker omdat het consent op een hoger nivo gegeven wordt.

**Comment by kvoer** [comment]
> Overwegingen:
> 
> * Consent kan worden gegeven op het niveau van een Bestuur of een School met meerdere digiDeliveryIds. Dit resulteert in een reeks van consentafspraken voor iedere individuele digiDeliveryId. In het Ecosysteem wordt dus altijd in de context van een enkele digideliveryId gecommuniceerd.
> * De school is in sommige data-objecten ook echt een entiteit die van belang is. Bijvoorbeeld als koper van de Entitlement. - Entitlements moeten ook verstuurd kunnen worden voor een particulier (Personal Entitlement). Hier is de school niet bekend. Hoe implementeren we in dat geval het plaatsen van Links in het LMS? En van wie is Consent nodig? Ook van de Particulier die koopt?
> 
> Voorstel tot besluit:
> 
> * In het token wordt de benaming schoolidentifier gebruikt. Dit is om veilig te communiceren in een context van instemming door de school (Consent).
> * In de APIs wordt het SchoolId gebruikt zodra de school een entiteit is. Bijvoorbeeld als Koper van de Aanspraak (Entitlement API). Of als School waar Leerlingen, Leraren, SchoolPerioden, SchoolVakken en Groepen zijn (SIS API). We hanteren dan schoolId.
> * In beide gevallen gaat het om het digiDeliveryId. En deze zijn veelal gelijk. Een Entitlement gekocht door School A (schoolId) betekent ook dat er een Token moet zijn voor School A (schoolidentifier) waarbinnen MP en LMS met elkaar communiceren.

In de werkgroep van 30 november 2022 is dit voorstel besproken. Het advies is om dit voorstel te volgen. Dit heeft een aantal voordelen:
- De MP kan naar een LA alle entitlementberichten van alle scholen (of individuen). Omdat hier geen consent voor nodig is hanteert de MP een token zonder schoolIdentifier. In het entitlementbericht is om deze reden ook de schoolId noodzakelijk. Zie ook issue #68 over toelichting onderscheid schoolIdentifier en schoolId.
- De MP kan naar een LMS alle entitlementberichten van alle LAs voor een enkele school sturen. Omdat hier consent voor nodig is hanteert de MP een token met schoolIdentifier. De gegevenstransactie vindt plaats in de context van de school.
