### ISSUE TITLE
Usage of UserId

### ISSUE THREAD

**Issue by hhaarsma** [stichtingsem/ecosystem#105]
For Student identification we can use EckId or UserId - and UserId then can contain either the NEPRI or the NEPPI.

If we communicate based on UserID - how do we know if this is either NEPRI or NEPPI? Do we risk issues if partners work based on different identifiers? Can this also have impact on the access clicks into the LA?

**Comment by kvoer** [comment]
In de werkgroep Summatieve Toetsresultaten is een voorstel gedaan om een ID een combinatie te laten zijn van het ID zelf en het registratietype. Bijvoorbeeld:

[XXXXXXX, ECK iD]
[YYYYYYY, NEPRI]
[ZZZZZZZ, NEPPI]

Waarbij we een ENUM hanteren voor de registratievariant en een voorkeur voor ECK iD hebben. Hiermee lossen we ook op dat de ID altijd gevuld moet zijn.

**Comment by edwinverwoerd** [comment]
> In de werkgroep Summatieve Toetsresultaten is een voorstel gedaan om een ID een combinatie te laten zijn van het ID zelf en het registratietype. Bijvoorbeeld:
> 
> [XXXXXXX, ECK iD] [YYYYYYY, NEPRI] [ZZZZZZZ, NEPPI]
> 
> Waarbij we een ENUM hanteren voor de registratievariant en een voorkeur voor ECK iD hebben. Hiermee lossen we ook op dat de ID altijd gevuld moet zijn.

_Goed voorstel, maar let op dit geldt alleen binnen de context van de M2M operaties._

**Comment by kvoer** [comment]
Voorstel tot besluit hierboven is ge-edit op basis van de discussie in de werkgroep.

**Comment by Jorimvdw** [comment]
Akkoord
