### ISSUE TITLE
Case sensitivity of properties

### ISSUE THREAD

**Issue by mrVanderWel** [stichtingsem/ecosystem#106]
Are properties of a request or response body case sensitive?

Example:
a GET request to /products results in a response containing Product objects, which contain some properties that have names that start with upper case letters (FirstPublishedDate, DeprecationDate, SupportedUntilDate, EndOfLifeDate). Is it allowed to respond with objects containing property names which all start with lower case letters? (specifically firstPublishedDate, deprecationDate, supportedUntilDate, endOfLifeDate)

**Comment by kvoer** [comment]
Voorstel tot besluit: alle attributen volgens de gelijke conventie hernoemen. En dan case sensitivity verplichten.

**Comment by edwinverwoerd** [comment]
> Voorstel tot besluit: alle attributen volgens de gelijke conventie hernoemen. En dan case sensitivity verplichten.

_AKKOORD, denk alleen wel dat het goed is om binnen de documentatie een aantal algemene verwerkingsregels te noemen en bij sommige attributen het expliciet te noemen_

**Comment by kvoer** [comment]
Voorstel tot besluit:
We hanteren de conventies van iedere standaard die we adopteren (bijvoorbeeld CMI5)
Voor de eigen APIs hanteren we de conventie dat ieder attribuut begint met een kleine letter, en gevolgd wordt door een Hoofdletter. Bijvoorbeeld schoolSubject, endOfLifeDate en dus niet SchoolSubject en EndOfLifeDate.
