### ISSUE TITLE
New field `start_date` for product in Catalogue API

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#11]
### Should we add a new field `start_date` to products within the Catalogue API?

The current Catalogue API has the `status` field in the `product` definition. The value could be `active` and `not-for-sale`. A MP and LMS does not know when a product becomes available for sale. In the new `start_date` field this information can be shared.

**Comment by mcginkel** [comment]
Fully agree, can we also think about end data? That will give the option to know that this product will no longer be available in the future. Great if you can see that in may already that a product wont be available next year.

**Comment by edwinverwoerd** [comment]
Validation on the current ECK DT Catalogue standaard is needed for this so that we made the changes in 1 run. Validation by admin track is needed for this.

**Comment by hhaarsma** [comment]
I think there is also a state between active and ended - when the product is no longer being sold, but usage is still possible.
For MP the date that it is not possible anymore to sell it is important. And for an LMS the end date of the product on the digital platform is importante.
And for new products I assume there is something similar where it could be possible to already buy the product, but not yet use it on the platform (Pre-Sales?).

**Comment by mcginkel** [comment]
@edwinverwoerd Any progress on this? Can we add the fields?

**Comment by edwinverwoerd** [comment]
In the current ECK DT Catalogus service the following information is available:

 FirstPublishedDate = De eerste verwachte verschijningsdatum van het product in the markt. {Pre-sales information)

DeprecationDate = Product niet meer leverbaar, eventueel nog wel ondersteund

SupportedUntilDate = Product niet meer gegarandeerd beschikbaar, niet meer ondersteund

EndOfLifeDate = Product verwijderd uit catalogus. Men wil vooraf inzicht verschaffen over het moment waarop een product niet meer leverbaar is, zodat afnemers hier rekening mee kunnen houden in hun keuze 

What we miss is a notification or end date that the information will not be shared anymore. But this is maybe covered by the principal of ussing the event message bus / information webhook .....
