### ISSUE TITLE
SIS data - do we need to pay attention to school start situation?

### ISSUE THREAD

**Issue by hhaarsma** [stichtingsem/ecosystem#110]
As Learning Application Noordhoff is only interested for the platforms in the current state of the SIS data, so no historical data or time span for intended use is present.
In preparation of school start a lot of changes are done on SIS data:
- removing all students from groups
- removing groups
- creating groups
- adding students to groups

How do we want these changes to propagate throught the eco-system? Are we going to communicate changes per student/group? Do we need some bulk operation option (could also be used by the initial seed)?

**Comment by kvoer** [comment]
Het voorstel van #119 om een initial seed toe te voegen aan iedere API kan bijvoorbeeld tijdens de technische schooljaarovergang op een gezamenlijk afgesproken moment gebruikt worden.

**Comment by edwinverwoerd** [comment]
hhhmm is er straks nog wel sprake van een schooljaar overgang?? En hoe lang moet deze initial seed voor SIS maar ook voor Entitlements etc dan actief blijven? En hoe voorkomen we dat er dan geen oude / niet actuele data ineens weer gaat leven.

**Comment by kvoer** [comment]
> hhhmm is er straks nog wel sprake van een schooljaar overgang?? En hoe lang moet deze initial seed voor SIS maar ook voor Entitlements etc dan actief blijven? En hoe voorkomen we dat er dan geen oude / niet actuele data ineens weer gaat leven.

Voor je vragen over de historische data van entitlements is een voorstel opgenomen in issue #112

**Comment by kvoer** [comment]
Dit issue is besproken tijdens de werkgroep van 30 november 2022. In de periode vanaf juni zullen scholen de voorbereidingen gaan treffen voor het komende schooljaar. Vanaf dat moment zullen de LAS-sen de wijzigingen door gaan sturen. Aangezien niet alle scholen dit op hetzelfde moment doen, zullen ook de berichten niet in één keer verstuurd worden. Om deze reden is het voorstel om niet een separate afspraak te maken voor het uitwisselen van gegevens voor de start van het schooljaar. Partijen ontvangen via events de wijzigingen in de schooladministratie vanuit het SIS.

**Comment by Eysbach** [comment]
Deze activiteiten vinden allemaal plaats ter voorbereiding van het nieuwe schooljaar enerzijds en ter afsluiting van het huidige schooljaar anderzijds. 
Om de start van het schooljaar goed voorbereid te beginnen, is het wenselijk dat een school groepen/docenten/roosters/studenten etc. conceptueel kan klaarzetten, zonder dat de indeling van het huidige schooljaar aangetast wordt. Vergelijk het met een webcms, waar je pagina’s “onderwater” kunt opbouwen en een datum kunt bepalen wanneer deze “active” worden en de oude “inactive”
Bedenk daarbij dat schoojaren in het MBO kunnen afwijken van de gebruikelijke schooljaren in het VO.

**Comment by Eysbach** [comment]
Deze activiteiten vinden allemaal plaats ter voorbereiding van het nieuwe schooljaar enerzijds en ter afsluiting van het huidige schooljaar anderzijds. 
Om de start van het schooljaar goed voorbereid te beginnen, is het wenselijk dat een school groepen/docenten/roosters/studenten etc. conceptueel kan klaarzetten, zonder dat de indeling van het huidige schooljaar aangetast wordt. Vergelijk het met een webcms, waar je pagina’s “onderwater” kunt opbouwen en een datum kunt bepalen wanneer deze “active” worden en de oude “inactive”
Bedenk daarbij dat schoojaren in het MBO kunnen afwijken van de gebruikelijke schooljaren in het VO.

Een “initial seed” (zie ook uitwerking van werkgroep 30 nov2022) is bedoeld als eerste opstart van een systeem en/of migratie, niet om jaarovergangen te ondersteunen.
Er wordt impliciet een “harde” datum voor een gezamenlijke jaarovergang voorgesteld. Het is zinvol te benoemen welke objecten in het Ecosysteem 100% voldoen aan afloop op een gezamenlijke vaste datum en welke niet (voor het MBO en het VO). 

De wijzigingen via events ontvangen is uiteraard vanzelfsprekend in het nieuwe SEM-Ecosysteem. 
Echter het faciliteren van scholen om (zoveel mogelijk) voorbereidende administratieve werkzaamheden in juni te verrichten voor het nieuwe schooljaar blijft een aandachtspunt voor het Ecosysteem. De vraag is of hier voldoende functionaliteit voor aanwezig is.
Denk daarbij ook met name aan het werken met de (vernieuwende!) subject-entitlements op basis van “subjects/groepen”, die een school in de SIS al klaar heeft gezet voor het nieuwe schooljaar. Hierdoor is het niet nodig te wachten op activiteiten van scholen die pas half augustus starten en entitlements die pas in augustus (of later) verstuurd kunnen worden.

Alle aspecten, technisch, administratie, functioneel, in de periode mei/juni/juli/aug voor VO en MBO t.a.v. de start van “een schooljaar” doornemen, verdient meer aandacht dat alleen dit ene issue 110. 
“YES”, we need to pay attention to school start situation!

**Comment by kvoer** [comment]
De feedback is besproken in de werkgroep van 9 december 2022. In het SEM Ecosysteem zijn al diverse maatregelen genomen die rekening houden met de start van het schooljaar. Onder meer:
- Entitlements kunnen ieder moment verstuurd worden.
- De datumvelden in de entitlement geven de ruimte om specifiek een activatie- en gebruiksperiode te definiëren.
- Leerlingen, Groepen en Leraren worden voor een schoolperiode en school gestuurd. Zo is het mogelijk om gegevens over het heden en de toekomst te versturen.

Functioneel en technisch is het hierdoor mogelijk om situaties omtrent de start van het schooljaar te ondersteunen.
