### ISSUE TITLE
Initial seed and catch-up Entitlements, Usage en Progress

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#112]
During the PoCs we encountered a few issues in the exchange of data in the Entitlements, Usage, and Progress API. The use cases were:
- There was no consent active between two parties.
- The consent has been deactivated between two parties for a period.
- The consent started at a later moment in time.

In all three cases there was a lack of information that should have been send between parties. For the SIS API we have an initial seed implemented to get the current actual state of all data. For the Entitlement, Usage, and Progress API we do not have this.

In addition we have the Webhook requests API to receive all events that have been send between the party for a specific school with consent. This endpoint does not register all events for the school but only those events that have been send to the party that had consent.

The above situation potentially leads to loss of data and misunderstanding about who is responsible for requesting or sending data. How could we solve these issues with protocol, initial seed endpoints or other solutions?

**Comment by edwinverwoerd** [comment]
In de praktijk gaan we dit niet voorkomen. Er zal dus een werkingsregel moeten komen waarin we beschrijven wat te doen bij. Met als basisregel dat als je de een "ondebreking" hebt de dat op basis van het gegeven consent de actuele data ophalen. En vanaf dat punt weer verder gaan.

Natuurlijk lopen we dan tegen het probleem wat en voor hoelang moet je de historische data meegeven. Denk aan een entitlement die ergens in de tussen liggende tijd wordt geannuleerd. Terwijl de SP deze entitlement nog als "actueel" heeft staan. De vraag is dus hoe lang wordt historische informatie meegegeven.    Deze vraag van van hoelang moet bij de business neergelegd worden.

**Comment by kvoer** [comment]
Dit voorstel is besproken in de werkgroep standaard van 30 november:
- Voor een tijdelijke onderbreking (waarbij consent actief is) kan een consumer gebruik altijd de niet ontvangen events opvragen.
- Voor een periode zonder consent is dit niet mogelijk. Het is voorstelbaar dat dit in de praktijk wel voorkomt.
- Ook is het mogelijk dat een school van het ene naar het andere systeem overstapt of een tweede systeem operationeel heeft.

Voor deze situaties is het wenselijk dat er werkingsregels worden afgesproken voor het versturen van _historische_ entitlement, usage en progress informatie. De voorstellen zijn:
1. Entitlement informatie: alle actieve entitlements in hun actuele status voor de school. Dus niet de tussenliggende events die gestuurd zijn. LA en LMS reageren conform het protocol op deze events met een entitlementConfirmation, waarbij additioneel geldt dat een LMS ook op een status die al linkReady is reageert met een linkReady (de link wordt opnieuw geplaatst, ondanks dat dit voorheen al gebeurd is). De MP weet dan dat ook in dit LMS een link is geplaatst.
2. Usage informatie: alle usage informatie van alle actieve entitlements voor de school.
3. Progress informatie: alle progress informatie van alle studenten van de school voor het lopende schooljaar.

**Comment by Eysbach** [comment]
Of je wel of niet informatie kan vrijgeven of ophalen wordt in het Ecosysteem geregeld op basis van consent. Dit is op het niveau van gegevens behorend bij één school(-locatie).
Maar voor historische gegevens blijkt er naast de consent ook nog behoefte te bestaan aan “werkingsregels”. Dat is iets wat dan ter aanvulling komt op de “consent en scoping” principes. Dat is wat vreemd, maar vooral ook “softer” bij de uitwerking in implementatie.
Als duidelijk is wie de eigenaar van de data is, nu en in het verleden, kan deze ook altijd consent geven over afwijkende periodes onafhankelijk van de partijen die hiervoor verwerkers zijn geweest. Het is daarom van belang om dit voor de verschillende dataobjecten duidelijk te hebben.
Hierbij komt ook het vraagstuk naar boven hoe lang historische data en/of events bewaard moeten blijven.
De oplossing heeft dus wat meer achterliggende overwegingen nodig, dan het huidige voorstel omvat.

**Comment by kvoer** [comment]
Review van It's Learning:

Probeer me de praktische scenario’s voor te stellen. Stel een school stapt over op ons. We zullen altijd moeten kunnen achterhalen welke entitlements een gebruiker nu heeft. Maar ik kan me ook goed voorstellen dat we ook willen weten welke progress een leerling had op een resource. Er staat nu dat deze info 'vanaf de start van het schooljaar' beschikbaar is. Is dat niet wat te beperkt? Je kunt steeds flexibeler met methodes werken (delen van jaar 2 als in jaar 1 behandelen). Stel je stapt in jaar 2 over van ons. Dan zouden we toch ook willen weten wat de progress van vorige schooljaar was?

**Comment by kvoer** [comment]
De review is besproken tijdens de werkgroep van 9 december 2022. Het voorstel van de werkgroep is om allereerst ervaring op te doen met de algemene afspraken zoals hierboven genoemd. Op basis van praktijkervaring kunnen deze afspraken bijgesteld worden. Daarnaast is het altijd mogelijk om bilateraal afwijkende en aanvullende afspraken te maken.
