### ISSUE TITLE
Hoe gaan we om met individueele kennisnet accounts

### ISSUE THREAD

**Issue by mcginkel** [stichtingsem/ecosystem#113]
geeft problemen bij de uitgevers omdat er later een ontdubbeling moet komen .

Bron: gesprek op 5 july22 met blink en leslab (koen,Kees)

**Comment by kvoer** [comment]
Voorstel tot besluit:

In het SEM Ecosysteem gaan we uit van single-sign-on via federatieve inlog. De IdP van de school moet er voor zorgen dat de attributen eckId (of userId) en schoolId meegestuurd worden.

Alle andere vormen van inlog, waaronder individuele kennisnet accounts, worden niet ondersteund.

**Comment by kvoer** [comment]
In de werkgroep van 9 november is besproken dat deze variant zal leiden tot een uitzondering bij de LA. De gebruiker komt in een flow terecht om zijn identiteit (eckId / userId en/of schoolId) te achterhalen. Of de gebruiker krijgt de optie om een activatie buiten het SEM Ecosysteem te kunnen doen. Bijvoorbeeld een activatiecode.

**Comment by Eysbach** [comment]
> Voorstel tot besluit:
> 
> In het SEM Ecosysteem gaan we uit van single-sign-on via federatieve inlog. De IdP van de school moet er voor zorgen dat de attributen eckId (of userId) en schoolId meegestuurd worden.
> 
> Alle andere vormen van inlog, waaronder individuele kennisnet accounts, worden niet ondersteund.

**RE: Wij hebben duizenden gebruikers met een individueel kennisnet account. Het is eenduidiger als deze alleen maar federatief kunnen inloggen. Daar wordt de systematiek eenvoudiger van. Maar de vraag is of we dit zomaar kunnen doen:
- Kennisnet laat op dit moment de keuze bij de gebruiker zelf. Kennisnet moet dus faciliteren dat dit niet meer kan. 
- Het inloggen is niet zozeer het probleem. De vraag is hoe de gebruiker aan zijn licentie komt. Op dit moment wordt dit alleen ondersteunt met een activeringscode.**

**Comment by Eysbach** [comment]
> In de werkgroep van 9 november is besproken dat deze variant zal leiden tot een uitzondering bij de LA. De gebruiker komt in een flow terecht om zijn identiteit (eckId / userId en/of schoolId) te achterhalen. Of de gebruiker krijgt de optie om een activatie te doen van een leermiddel dat buiten het SEM Ecosysteem is verkocht (bijvoorbeeld via een activatiecode).

**RE: Er staat hier dat een activeringscode buiten het SEM Ecosysteem zal gaan vallen. Het is wenselijk dat ook met activeringscodes gebruikers toegang kunnen krijgen via het Ecosysteem.**

**Comment by Eysbach** [comment]
Geen akkoord. Nog vraagtekens t.a.v. Kennisnet en activeringscodes.

**Comment by edwinverwoerd** [comment]
Voorstel om dit punt door te zetten naar Sprint 3. ! 

En er een extra punt aan toe te voegen:
**Gebruik activeringscode(s) binnen SEM Ecosysteem**. Rationale hierachter is dat we binnen de huidige keten deze type van levering (en ontsluiting) toepassen. Daarnaast is het een bouwsteen in de B2C markt waarbij de betaler niet de echte gebruiker is..

**Comment by kvoer** [comment]
In de werkgroep van 18 november is de feedback besproken:
- In het Ecosysteem is het van belang dat gebruikers op een correcte wijze worden gekoppeld aan hun geldende identifier in het Ecosysteem. In alle gegevensuitwisselingen (bijvoorbeeld usage, progress en results) wordt deze identifier gebruikt.
- Het is om deze reden niet wenselijk om de route van Kennisnet individuele accounts te ondersteunen. Echter in het SEM Ecosysteem kunnen geen afspraken gemaakt worden om deze route al dan niet te sluiten.
- De opmerking over activeringscodes staat los van dit issue Kennisnet individuele accounts en betekent een uitbreiding van het SEM Ecosysteem. Aan de stuurgroep wordt voorgelegd of we deze uitbreiding als onderdeel van versie 1.3 willen uitwerken of willen uitwerken in een volgende versie.
