### ISSUE TITLE
Uitzonderingen DigideliverIds

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#114]
Hoe gaan we om met uitzonderingen digideliveryId als unieke identifier voor school. Onder meer: scholen met meerdere digideliveryids, een digideliveryid voor meerdere scholen, wijzigingen van digideliveryid als gevolg van fusies of splitsingen.

**Comment by kvoer** [comment]
Voorstel tot besluit: in kaart brengen van uitzonderingen. En bij voorkeur oplossing zoeken in persistentie van schoolId.

**Comment by edwinverwoerd** [comment]
> Voorstel tot besluit: in kaart brengen van uitzonderingen. En bij voorkeur oplossing zoeken in persistentie van schoolId.

> _AKOORD en ik wil deze wel uitzoeken!_

**Comment by kvoer** [comment]
@stichtingsem/reviewgroep-standaard hebben jullie hier voorbeelden van?

**Comment by Jorimvdw** [comment]
_En bij voorkeur oplossing zoeken in persistentie van schoolId._
Wat wordt hiermee bedoeld?

**Comment by edwinverwoerd** [comment]
> _En bij voorkeur oplossing zoeken in persistentie van schoolId._ Wat wordt hiermee bedoeld?

_Deze opmerking is inmiddels achterhaald. digiDeliveryId in relatie tot schoolId is persistent. En hiermee dus geen issue._
