### ISSUE TITLE
Licentieperioden in product Catalogue API

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#116]
Een product heeft nu één licentieperiode. Voorstel is om hier een Array van te maken met bijvoorbeeld een maand, jaar of schooljaar. Nu moet voor iedere licentieperiode een nieuwe product toegevoegd worden.

Het is wel al mogelijk om meerdere businessmodellen toe te voegen. Waarom dan ook niet meerdere licentieperioden?

Mogelijk leidt dit ook tot wijziging van het Entitlement object. Omdat duidelijk moet zijn welke licentieperiode en businessmodel verkocht is door de MP.

**Comment by kvoer** [comment]
Ten aanzien van dit issue is het van belang om het volgende te overwegen:
- Een product in de Catalogue API dat _forSale_ is, is een verkoopbare eenheid en heeft een EAN.
- Een EAN heeft één prijs en betreft een uniek product.

Vanuit deze regels is het **niet** mogelijk om meerdere licentieperioden met meerdere prijzen op te nemen. Dit geld overigens ook voor meerdere prijzen in de businessmodellen. Desondanks kunnen er wel meerdere _model_ objecten gekoppeld zijn aan een product uit de Catalogue API. In het _model_ wordt immers ook een referentie gemaakt naar een identifier die door zowel LA als MP wordt herkend. Deze kan verschillen per relatie LA en MP.

Daarnaast bevat het Product het attribuut relatedProducts. Dit attribuut kan gebruikt worden om te refereren naar dezelfde producten met een andere licentieperiode.

Voorstel tot wijziging:
- Voorstel tot toevoegen array met licentieperiode niet honoreren.
- Overwegen om Businessmodels geen Array maar een Object te maken.

**Comment by edwinverwoerd** [comment]
Input voor de discussie:
1. Meerdere prijzen gekoppeld aan het EAN is verboden. Het is de fabrieksafprijs van het product dat omschreven is. NB: als het product een set is aan producten(subproducten binnen de catalogus onder de verkoopbare eenheid dan geldt de prijs voor de set.
2. Prijs is dus voor iedere MP in de basis gelijk. 
3. Array omzetten naar Object is okay
4. id hernoemen naar ContractID wil ik graag zien en bespreken. Ben er voor alsnog geen voorstander van.
5. aparte scope voor commerciele informatie partij specifiek is niet nodig als we uit blijven gaan dat het om fabrieksaf informatie gaat.
6. VAT toevoegen lijkt me zinvol, Maar moeten wederom toetsen hoe dit dan moet ingeval van een combi product.

**Comment by kvoer** [comment]
In de werkgroep bijeenkomst van 9 november zijn de wijzigingsvoorstellen besproken. Hierbij is het volgende overwogen:
- Iedereen was akkoord om het verzoek tot meer licentieperioden bij één product niet te honoreren. Dit zijn andere verkoopbare eenheden en hiervoor geldt een nieuw EAN.
- Het businessmodel bestaat uit de prijsmodel en het betaalmodel (prepaid, postpaid of periodiek). Het prijsmodel is voor iedere EAN uniek. Een EAN kan één of meerdere betaalmodellen ondersteunen.
- Het VAT tarief voor combi producten (fysiek en digitaal) kan complex zijn om te bepalen.
- Het id dat herkend wordt door MP en LA is overbodig. In de catalogus worden fabrieksprijzen gecommuniceerd. Informatie over kortingspercentages en specifieke contractafspraken tussen MP en LA zijn geen onderdeel van de Catalogue API. Om deze reden is een aparte scope la.catalogue_commercial ook niet noodzakelijk.

De definitieve wijzigingsvoorstellen zijn:

- Voorstel tot toevoegen array met licentieperiode niet honoreren.
- Array Businessmodel verwijderen en vervangen door price en betaalmodel.
- Object Price toevoegen bestaande uit: price_excl (exclusief VAT), price_incl (inclusief VAT), price_period, price_currency
- Nieuwe Array payment_models toevoegen waarin één of meerdere payment_models. Een palmet_model is een ENUM met de opties: "pre-paid", "post-paid", "periodically-paid".

**Comment by Jorimvdw** [comment]
Akkoord

**Comment by Eysbach** [comment]
De definitieve wijzigingsvoorstellen zijn:
•	Voorstel tot toevoegen array met licentieperiode niet honoreren.
**Mee eens. Argumentatie inderdaad: 1 EAN – 1 licentieperiode**
•	Array Businessmodel verwijderen en vervangen door price en payment_models.
**Mee eens**
•	Object Price toevoegen bestaande uit: price_excl (exclusief VAT), price_incl (inclusief VAT), price_period, price_currency
**Mee eens. Verduidelijking nodig op price_period. Logischer lijkt price_startdate price_enddate**
•	Nieuwe Array payment_models toevoegen waarin één of meerdere payment_models. Een payment_model is een ENUM met de opties: "pre-paid", "post-paid", "periodically-paid".
**Mee eens.**

**Comment by kvoer** [comment]
In de werkgroep van 18 november is de feedback besproken:

De benaming van pricePeriod heeft betrekking op de duur van de licentie (maand, kwartaal of jaar). Echter deze kan ook worden gelezen als de periode waarin de prijs geldt.

Om deze verwarring te voorkomen stellen we ten aanzien van dit attribuut het volgende voor:
- Verwijderen van attribuut pricePeriod uit het object Price.
- Opnemen van een attribuut _licensePeriod_ met de duur van de licentie of het abonnement. Bijvoorbeeld maand, kwartaal, jaar of schooljaar. Dit attribuut plaatsen we op het niveau van het product en is geen onderdeel van het object Price.
- Opnemen van een attribuut _validFrom_ met een datum tot wanneer de prijsstelling geldt in het object Price.
- In het product een Array met Price objecten opnemen (en dus niet één Price). Op deze manier kunnen er meerdere historische, huidige en toekomstige tariefstellingen gedeeld worden. En kan bijvoorbeeld een indexering tijdig worden gecommuniceerd.
- Werkingsregels opnemen dat er (indien deze bestaat) de vorige prijs (t-1), de actuele prijs (t) en indien bekend de toekomstige prijs (t+1) wordt gedeeld.

**Comment by linsegoeman** [comment]
- Voorstel tot toevoegen array met licentieperiode niet honoreren.
**Malmberg is het hiermee ook eens. Te complex om in de hele keten te werken met meerdere licentieduren per EAN.**

- Array Businessmodel verwijderen en vervangen door price en payment_models.
**Eens als er straks bij License ook een attribuut is meegegeven waarin we het soort licentie kunnen weergeven, dus schooljaarlicentie versus start bij activeren versus ...**

- Object Price toevoegen bestaande uit: price_excl (exclusief VAT), price_incl (inclusief VAT), price_currency
**Als we hier een echte catalogue api van willen maken die in de hele keten gebruikt kan worden om de artikelen te verkopen, dan is een VAT voor pakketten ook zeer relevant. Ik besef dat dit complexer is, maar wel te doen.**

- Nieuwe Array payment_models toevoegen waarin één of meerdere payment_models. Een payment_model is een ENUM met de opties: "pre-paid", "post-paid", "periodically-paid".
**Prima**
