### ISSUE TITLE
FDE Set attributen SIS API

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#117]
Niet alle attributen uit de FDE Set zitten al in de StudentDelivery API. Er ontbreken:
- Leerlingnummer
- Emailadressen van verzorgers
- Geslacht

Voegen we deze toe?

**Comment by kvoer** [comment]
De FDE-set wijkt af van de SIS API. Zie voor de specificatie het volgende bestand:

https://www.edustandaard.nl/app/uploads/2022/03/EDEXML-Profiel_FDE-setVO_1.2-20220309def.pdf

Per verschil hieronder een voorstel tot besluit

1. Uitwisseling scholen

**Comment by kvoer** [comment]
Ik vond in de oude Github nog onderstaand issue:

https://github.com/stichtingsem/technology-prototype/issues/28

Wellicht dat er nog perspectieven zijn die we moeten meenemen in ons wijzigingsvoorstel. Ik denk bijvoorbeeld aan het definiëren van de juiste scopes voor de SIS API. Dit zijn nu:

- sis.student-delivery - a scope that gives access to sensitive student information like adress
- sis.student-teacher-group - a scope that gives access to student, teacher and group data
- sis.school - A scope that allows access to the basic school information : periodes and schoolsubjects in those periods

Deze scopes wijken af van het initiële voorstel:

- las.user-identification - student or teacher, las ID, name and ECK ID.
- las.class-subject-membership - on top of user identification, you can request the classes, subjects and membership for student/teacher.
- las.user-delivery-information - for students, you can see the delivery information and DOB.

**Comment by SanneV1** [comment]
Is geslacht een waarde die nog nodig is?

**Comment by edwinverwoerd** [comment]
> Is geslacht een waarde die nog nodig is?
Ja in de tender wordt gevraagd om de communicatie persoonlijk te maken. En dan moet je soms iets met hij en zij (helaas)

**Comment by edwinverwoerd** [comment]
> De FDE-set wijkt af van de SIS API. Zie voor de specificatie het volgende bestand:
> 
> https://www.edustandaard.nl/app/uploads/2022/03/EDEXML-Profiel_FDE-setVO_1.2-20220309def.pdf
> 
> Per verschil hieronder een voorstel tot besluit
> 
> **A. Uitwisseling scholen** In de FDE-set worden scholen en FDE-vestigingen uitgewisseld. Gaan we dit in het SEM Ecosysteem ook doen? En vanuit welke rol?
> 
> Voorstel: Nader uitzoeken

> _AKKOORD_

> 
> **B. Entiteit Plaatsing** Aan een Leerling hangt de entiteit Plaatsing. Een Plaatsing bestaat uit:
> 
> * Schooljaar
> * Startdatum
> * Einddatum
> * Opleiding
> * Leerjaar
> 
> Voorstel: We wisselen in Ecosysteem via SIS API de Students uit naar SchoolPeriod. Dit maakt de entiteit Plaatsing overbodig.
> 

> ___Hoe borgen we de informatie over Opleiding en Leerjaar? Deze info is handig aangezien een leerling les kan volgen aan aan een andere opleiding binnen een ander Leerjaar!_ 

> **C Stam- en vakkengroepen** In de FDE-set worden Stamgroepen en vakkengroepen uitgewisseld. Gaan we dit onderscheid in de SIS API ook maken?
> 
> Vraag: wat is de use case voor stamgroepen?

> _Stamgroepen moet gezien worden als een soort van jaargroep binnen het VO. Maar binnen MBO is dit de groep cohort aanduiding waarin de student is gestart. Dit wordt meegenomen gedurende zijn loopbaan binnen het onderwijs. Denk dat het ook binnen het VO moet zo iets te gaan werken zeker als er sprake is van meer felexibiliteit. DUS GRAAG OVERLEGGEN _ 

> 
> **D. Attribuut Jaargroep** In de FDE-set wordt een attribuut Jaargroep gebruikt in de Stamgroep. Hier wordt een waardelijst gehanteerd: 11-16 voor vo V voor VSO
> 
> Voorstel: Jaargroep toevoegen bij Student.

> _Prima maar wel een even een toets met het voorafgaande. Maar volgens mij is het wel gedekt. TOP!_

> 
> **E. Entiteit Opleiding** Aan de Stamgroep. Vakkengroep en Plaatsing hangt de entiteit Opleiding. Een Opleiding bestaat uit:
> 
> * DUO-code
> * DUO-naam
> * School-profielcode
> * School-profielnaam
> 
> Voorstel: Opleiding toevoegen bij Student
> 

> _AKKOORD_

> **F. Entiteit Vak** Aan de Vakkengroep hangt de entiteit Vak. Een Vak bestaat uit:
> 
> * DUO-vakcode
> * DUO-vaknaam
> * School-vakcode
> * School-vaknaam
> 
> Voorstel: Vak niet toevoegen. We hebben SchoolSubject in SIS API

> _Graag nader toelichten of deze er echt uit kan. Plus validatie bij de review groep op basis van een voorbeeld._

> 
> **G. Leerlinginfo** Aan de Leerlinginfo hangt in aanvulling op Student Delivery Information
> 
> * Emailadres School
> * Emailadres Prive
> * Blok met E-mailadressen van Verzorgers
> * Geslacht met waardelijsten 0,1,2,9.
> * Gebruikersnaam
> * Leerlingnummer
> * Het adres is een blok bestaande uit straatnaam, huisnummer (volledig), postcode, woonplaats, landcode en Land. _Landcode_ ontbreekt in het huidige profiel.
> * FDE-vestiging
> 
> Voorstel 1: Adres in een Blok inclusief landcode 

> _Akkoord_

> Voorstel 2: E-mailadres school, prive en verzorgers toevoegen. 

> _AKKOORD_

>Voorstel 3: Geslacht toevoegen 

> _AKKOORD_ 

>Voorstel 4: Gebruikersnaam toevoegen 

> _Graag een discussie hierover en dat in samenhang met Voorstel 5. Gebruikersnaam het als verwerking het kenmerk waarmee de gebruiker inlogt. Ik vraag me echt af of we dit moeten delen. Er is een behoeften om voor inrichting anders systemen of voor bijvoorbeeld een migratie dat je een keyring wilt delen van sleutels. Waarbij het leerlingnummer; LeerlingID (technische sleutel); gebruikersnaam (?); ketenUserID (nietzijnde ECK-ID); ..... wilt uitwisselen. Maar laten we hiervoor dan binnen SEM ECO een aparte API definieren. Dan houden we het simpel_

>Voorstel_ 5: Leerlingnummer toevoegen 

> _Zie mijn opmerking bij Voorstel 4_

>Voorstel 6: FDE-vestiging is niet nodig omdat het SchoolId wordt uitgewisseld bij de Student

> _Weet eigenlijk niet wat hier nu staat. Wat is het verschil of gaat het om een verwerkingsregel definitie? _

> 

> 

> **H. Mutatiedatum** In alle gegevensobjecten is een mutatiedatum opgenomen.
> 
> Voorstel: Niet nodig om uit te wisselen. Dit gaat via Events.

> _Graag nader toelichten. Dit gaat alleen werken als binnen het gegevensobject dan wel het Events ID zit. Anders loop je het risico om in de tijd gezien out-of-sync te lopen!_

**Comment by kvoer** [comment]
Voorstel tot besluit hierboven is ge-edit op basis van de discussie in de werkgroep.
