### ISSUE TITLE
Format of digiDeliveryId

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#118]
Is het een ID of 'sleutel' die case-sensitive is en zonder wijziging?
We zien dat de data afhankelijk bij wie je het vraagt platgeslagen: zonder streepjes, alles in kleine letters.

**Comment by kvoer** [comment]
Voorstel tot besluit: Case sensitive en wijzigingen zijn niet mogelijk.

**Comment by edwinverwoerd** [comment]
Eens. Id is een string die we Case sensitive verwerken en de ontvangende partij verwekt deze 1 op 1 en geeft deze 1 op 1 door. Mag dus niet bewerkt worden.

ZIe ook de nieuwe FDE-profiel beschrijving met daarin de toelichting:  "Werkingsregel DigideliveryID : DigideliveryID is een externe sleutel (d.w.z. wordt extern bepaald en aangereikt) en case-sensitief. De waarde moet onbewerkt worden doorgegeven, dus geen omzetting naar hoofdletters of kleine letters."

**Comment by kvoer** [comment]
In de werkgroep is besproken dat het digiDeliveryId feitelijk altijd een persistentie identifier van een school is. In de praktijk komt het voor dat partijen niet op de laatste versie van het digiDeliveryId zitten. Dit is een data-integriteit vraagstuk en iets dat afgesproken dient te worden in de Afsprakenset. Dit is geen onderdeel van de functionele en technische oplossing.
