### ISSUE TITLE
SEM versus OneRoster

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#120]
Een van de partijen heeft gevraagd wat het verschil is tussen de SIS API en OneRoster. We hebben niet gekozen voor OneRoster omdat:

A. De benamingen meer overeenkomsten met het Hoger onderwijs in de Verenigde Staten. Het SEM Ecosysteem is gericht op het po, vo en mbo.

B. OneRoster geen rekening houdt met de volgende karakteristieken van het voortgezet onderwijs en middelbaar beroepsonderwijs:
- Niveau van onderwijs, bijvoorbeeld HAVO, VWO voor vo en Niveau 1, 2 voor mbo. Deze attributen zit niet in OneRoster.
- OneRoster gaat uit van een inschrijving voor een Vak in een bepaalde periode. In het po, vo en mbo is het nog meer de praktijk dat inschrijving gebeurt op een opleiding. En bij uitzondering op een vak van een ander niveau.
- In OneRoster wordt geen onderscheid gemaakt in stam- en vakkengroepen.

C. Er huidige implementaties van de SIS API zijn met de gekozen benamingen. Het wijzigingen van deze benamingen zou leiden tot extra werkzaamheden.

D. Het toevoegen van een OneRoster wrapper op de SIS API is mogelijk voor iedereen die dit wil doen. Hierbij dient wel rekening te worden gehouden met punt B.

E. OneRoster heeft een interessante specificatie van LineItems voor resultaten en hanteert waardelijsten voor Resultaten. Mogelijk kunnen deze als inspiratie dienen bij het uitbreiden van SimpleResult.

**Comment by kvoer** [comment]
Voorstel tot besluit: OneRoster niet opnemen. En verwijzen naar bovenstaande motivatie.

**Comment by edwinverwoerd** [comment]
> Voorstel tot besluit: OneRoster niet opnemen. En verwijzen naar bovenstaande motivatie. LineItems overwegen bij uitbreiding van SimpleResult

> _EENS we moeten inderdaad aan blijven geven dat we REGIONAAL en binnen het educatieve domein in NL opereren. We volgen hierbij ook de markt ontwikkelingen binnen dit domein.  _

**Comment by Jorimvdw** [comment]
Akkoord
