### ISSUE TITLE
Event API

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#122]
Tijdens het beschreven van de technische documentatie vielen me de volgende zaken op:
- schemaVersion is geen verplicht veld
- objectId is geen verplicht veld
- created heeft een nog niet besloten keuze voor de waarde van tijdstempel. Voorstel: datetime conform openapi in Zulu time
- schoolId zit in de berichtdefinitie van een Event. Is dit niet overbodig? Zie ook #104 
- De response op het POST endpoint /events en /event bevat een status en een statusMessage. De enige optie is hier status 0. Er wordt verwezen naar errors maar die kan ik niet vinden in de documentatie.

**Comment by edwinverwoerd** [comment]
Punt 1 = akkoord
Punt 2 = akkoord
Punt 3 = akkoord
Punt 4 = is niet overbodig moet in het eventbericht zitten. Zie genoemd issue
Punt 5 = er was toch een errorcode document in POC2 als onderdeel van de ppt;s die we aan het bespreken waren/besproken zijn. [NB waar staat deze oude documentatie eigenlijk].

**Comment by kvoer** [comment]
Zie de voorstellen zoals uitgewerkt in issue #68
