### ISSUE TITLE
UUIDs voor personen

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#125]
Uit de ROSA scan komt de volgende bevinding:

_Er wordt weliswaar gesteld dat een UUID alleen gebruikt mag worden binnen de context van een enkele resource, maar er lijkt verder niet afgedwongen te worden dat UUIDs niet over resources / calls heen gebruikt kunnen worden. Daarmee ontstaat mogelijk een separate persoonsidentifier naast de eigenlijke identifier (eckID, userID) die in de requests gebruikt worden._

En daarbij het volgende advies:

Werk uit welke eisen t.a.v. beveiliging worden gesteld aan de non-persistence van UUIDs voor personen.

**Comment by kvoer** [comment]
In de specificatie wordt dit ook niet consistent opgelost. Zo wordt er in de Usage API gebruik gemaakt van query parameters eckId en userId voor het opvragen van IndividualUsage:

https://stichtingsem.stoplight.io/docs/ecosystem/1af2d6ab3e34c-get-individual-usage

**Comment by edwinverwoerd** [comment]
Ja dit is nodig omdat we niet 1 waarde hebben. En in hybdride situatie moet we kunnen ondersteunen.

**Comment by kvoer** [comment]
Dit issue is besproken in de werkgroep van 30 november. Hierbij is het volgende voorstel geformuleerd:

**Overwegingen**
- In het Ecosysteem zijn endpoints noodzakelijk om voor een enkel individu (leerlingen en leraren) informatie op te vragen. Bijvoorbeeld zoals hierboven genoemd GET individual-usage.
- In het Ecosysteem is een endpoint aanwezig in de SIS API om gegeven van een enkele Student of Teacher op te vragen.
- In het Event bericht is een objectId opgenomen dat refereert naar de identifier voor een data-object dat in het event wordt verstuurd. Voor een Product is dit bijvoorbeeld de productId, voor een Course de courseId en voor een Student of Teacher een uniek UUID bepaald door het LAS. En dus niet het ECK iD of het userId.
- Het hanteren van een UUID voor Studenten en Teachers maakt het noodzakelijk dat een consumerende partij een dubbele administratie gaat voeren. Het UUID om een GET call te doen en het ECK iD en het userId voor alle andere communicatie. Daarnaast is het niet toegestaan om het UUID te gaan hanteren bij communicatie over een Student of Teacher in het Ecosysteem. Dit is verwarrend.
- Het opnemen van een ECK iD en/of een userId in een Path of Query parameter is niet wenselijk omdat deze informatie gelogd wordt. Ook kan dit leiden tot meerdere security issues.

We hebben voor bovenstaande een aantal zaken overwogen:
1. UUID hanteren in path parameter. Dit is niet wenselijk omdat a) alle GET endpoints voor specifieke users buiten de SIS API zoals de GET Individual Usage op de Usage API een dubbele administratie moeten voeren en b) er een nieuwe unieke identifier ontstaat die per abuis ook gebruikt kan worden als identificerend voor een leerling. 
2. ECK iD en userId in path of query parameter. Dit is niet wenselijk om security redenen.
3. ECK iD en userId opnemen in de Header. Dit is niet wenselijk omdat dit de implementatie complexer maakt en ook headers gelogd kunnen worden.
4. ECK iD en userId meenemen in de aanvraag van een Token en daarin opnemen. Dit betekent dat het probleem verlegd wordt. Ook hier zal er gebruik gemaakt moeten worden van een query parameters. Het is omwille van de OAuth standaard niet mogelijk om de POST body te hanteren.
5. Van de GET endpoints voor een enkele Student of Teacher een POST endpoint maken en het ECK iD en het userId opnemen in de Body. Deze is encrypted en wordt niet gelogd.

**Voorstel tot besluit**
Alle endpoints om informatie voor een enkel individu (Student of Teacher) op te vragen worden POST endpoints. Het ECK iD of het userId worden in de body meegestuurd. Het betreft:
- POST Search Student by ID, SIS API
- POST Search Teacher by ID, SIS API
- POST Search Individual Usage by ID, USAGE API

Deze implementatie is ook conform de suggestie zoals gedaan bij: https://codeql.github.com/codeql-query-help/javascript/js-sensitive-get-query/

Als gevolg van dit voorstel wordt het objectId voor Studenten en Teachers het ECK iD of het userID en niet meer de UUID zoals eerder gecommuniceerd in het event. In het Event bericht stellen we daarom de volgende wijzigingen voor:
- objectId voor Student en Teacher berichten wordt ofwel het ECK iD ofwel het userID.
- We voegen een nieuw veld toe objectIdType met een ENUM bestaande uit: ECK iD, en de waarden zoals reeds opgenomen in de waardelijst van userId.

**Comment by kvoer** [comment]
> Voorstel ziet er logisch uit, maar zolang niet alle users op eck-id zitten blijven we een hybride situatie behouden waar het SEM-Ecsysteem op ingericht moet zijn. Dat zit ook in het voorstel verweven (gebruik van nepri en neppi). Onderstaande situaties bestaan allemaal in de huidige keten. Daarbij kan tijdens of bij wisseling van het schooljaar, dit voor een bepaalde student veranderen. Het is dan vooral van belang dat een student daarna als dezelfde student geïdentificeerd kan worden. Dit is vooral van belang als deze overgaat van een combinatie naar “alleen eck-id”. Dat is dan weer niet nodig voor leerlingen die vanaf het eerste leerjaar al met een eck-id werken. In het voorstel kunnen twee (drie?) velden gevuld zijn, waarbij userIdType uiteindelijk bepaald wat de “objectkey” is. Hoe gaat het werken bij omzetten van deze waarde?
> 
> De combinaties eck-id – neppi – nepri (vooral bij mbo/vo scholen) eck-id – neppi eck-id – nepri neppi – nepri (vooral bij mbo/vo scholen) Of: alleen eck-id alleen neppi alleen nepri
> 
> Tenslotte nog de signalering dat docenten bij gebruik van meerdere “portals” telkens een ander eck-id hebben. Wat natuurlijk verrassend is, maar wel de praktijk. Dit zou in het nieuwe ecosysteem voorkomen moeten worden. Bij het loslaten van het UUID, weegt dit probleem uiteraard zwaarder.

De feedback is besproken in de werkgroep van 9 december. De problematiek van dubbele identifiers, wijzigingen van contextgevoelige identifiers zoals NEPPI en NEPRI zijn in ieder ecosysteem een issue. De huidige praktijk van was-wordt lijsten is één van de manieren die hiervoor gehanteerd kan worden. Ook is het een extra stimulans om te gaan naar het ECK iD als persistente identifier.
