### ISSUE TITLE
Uniforme Beveiligingsvoorschriften

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#126]
Uit de ROSA scan komt het volgende advies:

Maak duidelijk op welke wijze de Uniforme Beveiligingsvoorschriften (cf. www.edustandaard.nl) worden gehanteerd.

De links zijn:
- Security Headers: https://www.edustandaard.nl/standaard_afspraken/ubv-security-headers/uniforme-beveiligingsvoorschriften-security-headers-v1-0/
- TLS: https://www.edustandaard.nl/standaard_afspraken/uniforme-beveiligingsvoorschriften/uniforme-beveiligingsvoorschriften-transport-layer-security-tls-1-2/

**Comment by edwinverwoerd** [comment]
SPRINT 4.

**Comment by kvoer** [comment]
Dit issue is besproken in de werkgroep van 30 november 2022. De werkgroep gaat de UBV voorschriften doornemen op eventuele conflicten met principes gehanteerd in implementaties en/of documentatie van SEM Ecosysteem. De uitkomsten worden besproken in sprint 4.

**Comment by kvoer** [comment]
In de werkgroep van 12 januari 2023 zijn de UBV nogmaals besproken. Er zijn geen conflicten geconstateerd met de implementatie van de security principes binnen het Ecosysteem.

Voorstel tot besluit:
Voorschrijven van de UBV als vereiste voor de technische implementatie van het SEM Ecosysteem.

**Comment by kvoer** [comment]
In de reviewgroep is een vraag gesteld over de vereiste te hanteren certificaten. Conform iedere beveiligde SSL verbinding is er een certificaat noodzakelijk om gegevens veilig uit te wisselen en zeker te zijn van elkaars identiteit in deze gegevensuitwisseling.

Binnen Edukoppeling worden er ook PKI-overheid certificaten voorgeschreven. Edukoppeling is voor nu nog geen onderdeel van het SEM Ecosysteem en betreft een separaat issue #132.

**Comment by mrVanderWel** [comment]
Er zijn geen grote drempels om de UBV voor te schrijven, certificaten met een OIN erin worden wel genoemd in het TLS document maar slechts als optie. Wij hebben andere manieren om de doelgroep van onze requests te specificeren en hebben dus geen PKI-overheidcertificaat met OIN nodig. Ik zie ook geen bezwaren tegen het volgen van de voorschriften met betrekking tot de te hanteren headers; deze voorschriften zijn alleen van toepassing op het enige UI component van de SEM spec: de consent UI. Kortom: we kunnen zowel de TLS beveiligingsvoorschriften als de security headers voorschriften volgen.
