### ISSUE TITLE
Sensitive versus non-sensitive student information

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#127]
In de documentatie van de SIS API wordt het onderscheid gemaakt tussen sensitive en non sensitive informatie. Dit om het onderscheid te maken tussen generieke studentgegevens en specifieke gegevens noodzakelijk voor fijndistributie (thuisadres en emailadressen). Deze benaming is niet geheel correct aangezien de generieke studentgegevens ook persoonsgegevens betreffen. 

Voorstel: benaming sensitive en non sensitive verwijderen om verwarring te voorkomen.

**Comment by edwinverwoerd** [comment]
Prima
