### ISSUE TITLE
Unique identifier needed for ordering / purchasing organization?

### ISSUE THREAD

**Issue by edwinverwoerd** [stichtingsem/ecosystem#16]
Do we need an unique Identifier for an ordering/purchasing unit/organization. Examples:

-  school board, = OMO
-  purchasing organization = SIVON
-  school (location) unit = SCG Noordik Almelo - van Renselaan

Answer: we **do not need an unique identifier for** an organization. It is beter to **work with an unique contractI**D within the chain. Names /identifiers  are not pre-competitive. Sharing of this kind of information is prohibited

**Comment by edwinverwoerd** [comment]
The <contractId> is a part of the Entitlement API. So this can be used to make a relation between the **different** Entitlement**s** and the contract agreements between to Parties.  The the use of the attribute is NOT mandatory. This is because of the use of a Entitlement agreement with a private customer (MBO-scope).

**Comment by kvoer** [comment]
For now this issue is resolved with the DigideliverID. In committee on Purchase API the issue could be reopened.
