### ISSUE TITLE
Groups - design datastructure

### ISSUE THREAD

**Issue by TM-Frank** [stichtingsem/ecosystem#18]
Please some investigation about the datastructure en relations of Groups (regarding (SIS / MP)
I’m sorry, this is not in english language. Screenshot with questions for now. 

![image](https://user-images.githubusercontent.com/95485829/146525544-8d686997-93d5-4750-8005-43c0c42fdccd.png)

**Comment by mcginkel** [comment]
Question on Groups on SIS level:
- Can one group be part of multiple schools? Answer : No
- Is group the "Klas"? Not always, It is both the stamgroep and the Lesgroep. It is the way a group is used by a teacher. example: : these students are in group "H2a" or in "H4ena"
- Is subject choices part of a group and not  of a student? Answer : Both. A group is the group of students who will have one or more subjects together. In de "onderbouw" this is usually the "stamgroep" where most students have the same subjects. In de "bovenbouw" groups can also contain individual students from different stamgroepen that share one or more subjectchoices.
On individual level a student has his/her own subjectchoices.

All the above is to accommodate that some schools wont use groups at all.

**Comment by mcginkel** [comment]
All groups are scoped for one schoolyear in one school

**Comment by mcginkel** [comment]
Questions on Group MP:
Group is indeed very  confusing. The relation between entitlement on school level is via the subject choices of a student. In the entitlement it should be called subjectChoice. So to see which product the student is entitled to: 
1. take the eckid of the student, find the student in the SIS data, look at the subject choices and match these with the subject choices in the entilements for that school
2. look at the individual entitlements for a matching eckID

For a teacher: Only match on ECKID

**Comment by niesink** [comment]
I'm not sure I agree on the proposed definition of a subject choice. Particularly the notion that students can have the same subject choice. 

In my view a subject choice belongs to only one student and in that sense I agree with Frank that the weird thing / problem is that subjectChoice is currently missing a reference to the student.

Or to rephrase in different words: our understanding of a subject choice is it's the entity that says "this student is taking this subject on this level/year at this time/date and they're doing so as part of this group"

**Comment by TM-Frank** [comment]
The idea regarding "_and they're doing so as part of this group_" is that in current ecosysteem-flow, the LAS and LMS will be responsible to retrieve this group(s)-membership of a user directly from the SIS, using ECK-id. 
Note that this adresses a school-entitlement (compare ILF-specification).
If we are dealing with an indiviual-entitlement (compare ELF-specification), the student is ofcourse linked to the entitlement.

So an entitlement has in either cases (ILF an ELF) no Groupinformation at all (compare with "specfications" in current ECK-flows, where also no group-information is present)
The new way of working is, that the "matching/claim" process (ILF-specification), will not be based anymore on Kennisnet-data, but on the membership of school-group (by ECK-id,  linked tot the same subjectchoise of the entitlement.

**Comment by niesink** [comment]
Ok, I think I understand/agree. My only remaining point is that 'subject choice' does not refer to the thing that is chosen (i.e. _'Aardrijkskunde HAVO leerjaar 3'_) but rather the actual choice it self (i.e. _'Mark chose Aardrijkskunde HAVO leerjaar starting 15-04-2023 as part of H3.ak.2'_). 

So I think what should be linked to from an entitlement is not the subject choice but rather the subject (i.e. the subjectcode, level, year).

**Comment by TM-Frank** [comment]
I agree with you Luke. Subject would be better. "Choise" is indicating a relationship with an indidivual (that makes the choise).
