### ISSUE TITLE
Product not always EAN

### ISSUE THREAD

**Issue by TM-Frank** [stichtingsem/ecosystem#19]
A product will (in near) future not always be identified with an EAN.
My suggestion is to use an unique Ecossysteem ID for a product, together with an MP-specific identitfier what could be an EAN or a "contract-ID". 
Think of custommade (school scope) educational content that will not be present in a Catalogue

**Comment by edwinverwoerd** [comment]
For this we have to follow the discussion within Edustandaard ECK-DT. And for support reasons it is good to have the product in the catalogue but with clear metadata.

**Comment by TM-Frank** [comment]
What about the use of UPI defined in Edustandaard and supported in ECK 2.5 services as productID?

**Comment by edwinverwoerd** [comment]
This is now the topic of the discussion within Edustandaard. So please wait until that result. And yes we have to check what is in that standard and what is necessary for us in the ECO-system.

**Comment by TM-Frank** [comment]
Ok. But also as with a "user-entity", I think we should not use an external ID (ean) as primary key in the ecosystem.

**Comment by mcginkel** [comment]
After a few emails we decided to change to productId.
