### ISSUE TITLE
Terminology and definitions

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#3]
### What are the agreed upon definitions of key terms within the ecosystem?
Definitions that need to be defined:
- Entitlement
- Usage
- Progress

Definitions can be added to or edited in the [Glossary](https://github.com/stichtingsem/ecosystem/blob/master/glossary.md)

**Comment by kvoer** [comment]
We created a new definition for entitlements:
1. The right to use a digital learning material within an agreed upon period. This usage right can be sold and purchased.
2. A clear and unambiguous and transparent set of information required for all parties in the ecosystem to a) fulfil digital learning materials to the purchaser and its user(s) and b) specify, administer and control all financial transactions between the purchaser, the market place and the learning application.

This definition is under review in the functional and administrative track.

**Comment by TM-Frank** [comment]
Koen,

Mijn inbreng op de entitlement definitie (en statussen)

De gebruiker zelf is de enige met gebruiksrecht (license). Dit is een niet overdraagbaar gebruiksrecht.
Voordat de license door een gebruiker is geactiveerd is er nog sprake van een tegoed op gebruiksrecht.
Een entitlement gaat dus bij activatie over van status "tegoed op gebruiksrecht" naar "gebruiksrecht".

Het tegoed kan toegewezen zijn aan: (school / school.subject / school.individu / individu)
Het tegoed heeft een andere periode van geldigheid dan de licentie zelf. Vergelijk voorbeeld: Een saunabon is tot een jaar na datum in te wisselen, maar is na inwisseling maar één dag geldig.
Het gebruikrecht heeft dus andere kenmerken dan het tegoed op een gebruiksrecht.
Dat is de reden dat voorstel (1) niet kan, want we hebben te maken met verschillende statussen (levenscyclus) en dus kun je niet definieren op 1 statusmoment (als het recht geactiveerd is).
Ik sluit me eerder aan bij voorstel (2) maar dan een kortere versie.
Entitlement = An LicenseLabel that guides the process of fulfillment of licenses for using digital learning material.

Statussen van een Entitlement:
Planned    =  availableStartdate > Today                                                                   (Aangemaakt, maar nog niet inwisselbaar)
Available  =  availableStartdate < Today and availableEndDate > Today          (Licentietegoed / License Credit)
Active       =  activeStartdate < Today and activeEnddate > Today                             (Licentie)
Expired     = availableEndDate < Today or activeEnddate < Today                             (verlopen licentie)
Canceled  = State set by MP for any reason within its role and consent               (despecificatie of block)
Revoked   = State set by Admin for any reason within its role and accessrights        (ingetrokken)
Mvg
Frank



Frank 
 
Aarts
ICT projectleider / SCRUM-master

Smallepad 30 | 3811 MG Amersfoort
Postbus 400   | 3800 AK Amersfoort

T: 033 - 448 39 05
M: 06 53 89 52 63
E: ***@***.***
W: www.thiememeulenhoff.nl
🌲 Denk aan het milieu voordat u dit bericht print.

DISCLAIMER
Dit bericht is uitsluitend bestemd  voor de geadresseerde. Als u dit bericht per abuis heeft ontvangen, wordt u  verzocht het te vernietigen en de afzender te informeren. ThiemeMeulenhoff wijst  elke aansprakelijkheid af die voortvloeit uit elektronische verzending.
Van: Koen Voermans ***@***.***>
Verzonden: woensdag 2 februari 2022 08:51
Aan: stichtingsem/ecosystem ***@***.***>
CC: Aarts, Frank ***@***.***>; Assign ***@***.***>
Onderwerp: Re: [stichtingsem/ecosystem] Terminology and definitions (Issue #3)


We created a new definition for entitlements:

  1.  The right to use a digital learning material within an agreed upon period. This usage right can be sold and purchased.
  2.  A clear and unambiguous and transparent set of information required for all parties in the ecosystem to a) fulfil digital learning materials to the purchaser and its user(s) and b) specify, administer and control all financial transactions between the purchaser, the market place and the learning application.

This definition is under review in the functional and administrative track.

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstichtingsem%2Fecosystem%2Fissues%2F3%23issuecomment-1027669273&data=04%7C01%7Cf.aarts%40thiememeulenhoff.nl%7C6c62a470bdde423c1d0a08d9e620c42e%7Cb22b36d46d4b4114bd433913bc2d1225%7C0%7C0%7C637793850672151487%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CzWw8BOXDH15o1%2FxlMHbgRONtb7CGwTCSoW3CVyk%2FWQ%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWYP7BIQBGOBGZ6XEWBJQ3TUZDO6RANCNFSM5JGOIYWQ&data=04%7C01%7Cf.aarts%40thiememeulenhoff.nl%7C6c62a470bdde423c1d0a08d9e620c42e%7Cb22b36d46d4b4114bd433913bc2d1225%7C0%7C0%7C637793850672151487%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YIsIHsitcu%2BEcAgXqGUeeR3cnRynW8%2BBpFpZQasp7wA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cf.aarts%40thiememeulenhoff.nl%7C6c62a470bdde423c1d0a08d9e620c42e%7Cb22b36d46d4b4114bd433913bc2d1225%7C0%7C0%7C637793850672151487%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=glNbO%2FHkiaGpajScoThyPpC856K%2FmBUii3hjEMKvNfY%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cf.aarts%40thiememeulenhoff.nl%7C6c62a470bdde423c1d0a08d9e620c42e%7Cb22b36d46d4b4114bd433913bc2d1225%7C0%7C0%7C637793850672151487%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2exQKPDIhogMp5EHoPkZLh%2BX3wYutvKwCjACe56LZXs%3D&reserved=0>.

**Comment by TM-Frank** [comment]
Koen,

Nog een toevoeging van een typisch probleem uit de praktijk is het "stapelen van een licentie" bij entitlements met vaste doorlooptijd:
Een exact gelijk entitlement met vaste doorlooptijd, wordt toegewezen aan dezelfde persoon. Deze user wacht niet totdat deze een foutmelding van een verlopen licentie krijgt, maar een waarschuwing dat dit binnenkort gaat verlopen.
Als deze voortijdig wordt vervangen door een nieuwe licentie, resteren er nog dagen op de oude licentie, die worden "meegenomen" naar de nieuwe licentie/nieuwe einddatum.
Deze twee entitlements moeten dus één of andere kruisbestuiving hebben t.a.v. status, en start- en einddatum.
Afhankelijk van de implementatie hiervan, heeft dit nog gevolgen voor de status.
Dit is geen uitzonderingssituatie overigens, want dit is van toepassing bij ons op alle gebruikers in het Beroepsonderwijs.

Mvg
Frank


Frank 
 
Aarts
ICT projectleider / SCRUM-master

Smallepad 30 | 3811 MG Amersfoort
Postbus 400   | 3800 AK Amersfoort

T: 033 - 448 39 05
M: 06 53 89 52 63
E: ***@***.***
W: www.thiememeulenhoff.nl
🌲 Denk aan het milieu voordat u dit bericht print.

DISCLAIMER
Dit bericht is uitsluitend bestemd  voor de geadresseerde. Als u dit bericht per abuis heeft ontvangen, wordt u  verzocht het te vernietigen en de afzender te informeren. ThiemeMeulenhoff wijst  elke aansprakelijkheid af die voortvloeit uit elektronische verzending.
Van: Aarts, Frank
Verzonden: woensdag 2 februari 2022 12:55
Aan: stichtingsem/ecosystem ***@***.***>
CC: Koen Voermans ***@***.***>
Onderwerp: RE: [stichtingsem/ecosystem] Terminology and definitions (Issue #3)

Koen,

Mijn inbreng op de entitlement definitie (en statussen)

De gebruiker zelf is de enige met gebruiksrecht (license). Dit is een niet overdraagbaar gebruiksrecht.
Voordat de license door een gebruiker is geactiveerd is er nog sprake van een tegoed op gebruiksrecht.
Een entitlement gaat dus bij activatie over van status "tegoed op gebruiksrecht" naar "gebruiksrecht".

Het tegoed kan toegewezen zijn aan: (school / school.subject / school.individu / individu)
Het tegoed heeft een andere periode van geldigheid dan de licentie zelf. Vergelijk voorbeeld: Een saunabon is tot een jaar na datum in te wisselen, maar is na inwisseling maar één dag geldig.
Het gebruikrecht heeft dus andere kenmerken dan het tegoed op een gebruiksrecht.
Dat is de reden dat voorstel (1) niet kan, want we hebben te maken met verschillende statussen (levenscyclus) en dus kun je niet definieren op 1 statusmoment (als het recht geactiveerd is).
Ik sluit me eerder aan bij voorstel (2) maar dan een kortere versie.
Entitlement = An LicenseLabel that guides the process of fulfillment of licenses for using digital learning material.

Statussen van een Entitlement:
Planned    =  availableStartdate > Today                                                                   (Aangemaakt, maar nog niet inwisselbaar)
Available  =  availableStartdate < Today and availableEndDate > Today          (Licentietegoed / License Credit)
Active       =  activeStartdate < Today and activeEnddate > Today                             (Licentie)
Expired     = availableEndDate < Today or activeEnddate < Today                             (verlopen licentie)
Canceled  = State set by MP for any reason within its role and consent               (despecificatie of block)
Revoked   = State set by Admin for any reason within its role and accessrights        (ingetrokken)
Mvg
Frank


Van: Koen Voermans ***@***.******@***.***>>
Verzonden: woensdag 2 februari 2022 08:51
Aan: stichtingsem/ecosystem ***@***.******@***.***>>
CC: Aarts, Frank ***@***.******@***.***>>; Assign ***@***.******@***.***>>
Onderwerp: Re: [stichtingsem/ecosystem] Terminology and definitions (Issue #3)


We created a new definition for entitlements:

  1.  The right to use a digital learning material within an agreed upon period. This usage right can be sold and purchased.
  2.  A clear and unambiguous and transparent set of information required for all parties in the ecosystem to a) fulfil digital learning materials to the purchaser and its user(s) and b) specify, administer and control all financial transactions between the purchaser, the market place and the learning application.

This definition is under review in the functional and administrative track.

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstichtingsem%2Fecosystem%2Fissues%2F3%23issuecomment-1027669273&data=04%7C01%7Cf.aarts%40thiememeulenhoff.nl%7C6c62a470bdde423c1d0a08d9e620c42e%7Cb22b36d46d4b4114bd433913bc2d1225%7C0%7C0%7C637793850672151487%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CzWw8BOXDH15o1%2FxlMHbgRONtb7CGwTCSoW3CVyk%2FWQ%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWYP7BIQBGOBGZ6XEWBJQ3TUZDO6RANCNFSM5JGOIYWQ&data=04%7C01%7Cf.aarts%40thiememeulenhoff.nl%7C6c62a470bdde423c1d0a08d9e620c42e%7Cb22b36d46d4b4114bd433913bc2d1225%7C0%7C0%7C637793850672151487%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YIsIHsitcu%2BEcAgXqGUeeR3cnRynW8%2BBpFpZQasp7wA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cf.aarts%40thiememeulenhoff.nl%7C6c62a470bdde423c1d0a08d9e620c42e%7Cb22b36d46d4b4114bd433913bc2d1225%7C0%7C0%7C637793850672151487%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=glNbO%2FHkiaGpajScoThyPpC856K%2FmBUii3hjEMKvNfY%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cf.aarts%40thiememeulenhoff.nl%7C6c62a470bdde423c1d0a08d9e620c42e%7Cb22b36d46d4b4114bd433913bc2d1225%7C0%7C0%7C637793850672151487%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2exQKPDIhogMp5EHoPkZLh%2BX3wYutvKwCjACe56LZXs%3D&reserved=0>.
