### ISSUE TITLE
Delete objects

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#4]
### How do we deal with events that delete objects?
After removal parties in the ecosystem are not able anymore to request the object from the source. We could add a `type` to the event to tackle this issue.

**Comment by mcginkel** [comment]
Can you please give an example for this ? For me the description is still a bit unclear.

**Comment by Jorimvdw** [comment]
Example: student leaves school, his/her data is deleted in the SIS. An event is triggered and send to all webhooks. After the event is received, a call to the right endpoint is done to retrieve the changed data-object, but that object is not retrievable because it is deleted. This could be fixed be adding a type to an event. type could be create, update or delete.

**Comment by mcginkel** [comment]
I do not see the need to add created/updated as you can start halfway in an event stream.
Adding a Removed indicator is usefull. 
Kafka uses the idea of thombstone records. A kind of event that is the last you will ever receive about this entity, the data is then empty.

We can do the same: Data is empty, but that can conflict with no data and use the URL to get the event data pattern.
I think we should make it explicit: add an "thisIsAdeleteEvent" flag and leave the event empty. problem is : what is then deleted... so we need an identifier on the event, that is filled dependent on the type

|----event type: --|-- identifier--|
|-------------------|--------------|

| sis.group | id |
| catalog.product | ean |
| sis.student|  id (will become eckId) |
| sis.student-delivery|  id (will become eckId) |
| subjectChoice|  id |
| sis.teacher | id |

the following events do not need delete:
| usage.student | <No delete needed > |
| mp.entitlement.* | <no delete needed |
