### ISSUE TITLE
Setup and consent for parties in the ecosystem of the school

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#5]
### What protocol, authentication, and consent mechanism do we use to setup the ecosystem of a school?
Underlying questions to be answered are:
1. Which steps are involved in the setup protocol?
2. In what order?
3. Which steps are used in the consent protocol?
3. How to authenticate parties and their roles?
4. Do we use a central register of parties and their roles?
5. Is the OSR and/or Edukoppelingen a possible register we could use?
6. How does a party in the Ecosystem knows if a school has given consent?

**Comment by TM-Frank** [comment]
Discussion:
We also nee a scope-setting for the Catalog.
An LA should be able tot grant MP's to retrieve productinformation and schools should grant MP to retrieve their products from the catalog. Catalog has "private" and "public" products. Privat product kan only be retrieved if granted.

**Comment by kvoer** [comment]
Setup and Consent has been described in Consent Flow
