### ISSUE TITLE
Decide which values are valid for 'level'

### ISSUE THREAD

**Issue by niesink** [stichtingsem/ecosystem#55]
We need to determine which enumeration values are valid for the level fields as defined in:
* SchoolSubject.level in the SIS API and Entitlements API
* LevelSubject.level in the Catalogue API

We would like to reuse an existing list of values, e.g. the list of values used within RIO/DUO.

**Comment by niesink** [comment]
The following list seems like a good option. These are the values used within the RIO opendata dataset.
I'm still trying to get a definitive version of this list that is published online (and therefor can be referenced from our specification description).

|Waarde|Omschrijving|
|------|-------------|
|PO-VVE	    |Voor- en vroegschoolse educatie|
|PO-BAO	    |Basisonderwijs|
|PO-SBAO	|    Speciaal basisonderwijs|
|PO-SO	    |Speciale scholen|
|PO-VSO  	|Voortgezet speciale scholen|
|VO-PRO	    |Praktijkonderwijs|
|VO-VMBO-BB	|Voorbereidend middelbaar beroepsonderwijs, basisberoepsgerichte leerweg|
|VO-VMBO-KB	|Voorbereidend middelbaar beroepsonderwijs, kaderberoepsgerichte leerweg|
|VO-VMBO-GL	|Voorbereidend middelbaar beroepsonderwijs, gemengde leerweg|
|VO-VMBO-TL	|Voorbereidend middelbaar beroepsonderwijs, theoretische leerweg|
|VO-HAVO	|    Hoger algemeen voortgezet onderwijs|
|VO-VWO	    |Voorbereidend wetenschappelijk onderwijs|
|VO-VBO	    |Overig voortgezet onderwijs Geldig tot 01-01-2018|
|MBO	    |    Middelbaar beroepsonderwijs|
|MBO-1	    |MBO Assistent of Entree|
|MBO-2	    |MBO Basisberoep|
|MBO-3	    |MBO Vakopleiding|
|MBO-4	    |MBO Middenkader/specialist|
|NT2-I	    |Nederlands als tweede taal Programma 1|
|NT2-II	    |Nederlands als tweede taal Programma 2|
|EDUCATIE	|Educatie|
|HBO-AD	    |HBO Associate Degree|
|HBO-BA	    |HBO Bachelor|
|HBO-MA	    |HBO Master|
|HBO-PM	    |HBO Postinitiele Master|
|HBO-O	    |HBO Ongedeeld|
|WO-BA	    |WO Bachelor|
|WO-MA	    |WO Master|
|WO-PM	    |WO Postinitiele Master|
|WO-O	    |WO Ongedeeld|
|ONBEPAALD	|Niet vastgesteld

**Comment by niesink** [comment]
A more limited set of specifically the VO-values can be referenced to at this URI:
https://lod.onderwijsregistratie.nl/api/catalogus/v1/klasse?subject=http://lod.onderwijsregistratie.nl/cat/cdm/def/NiveauVO-v03.2

|Waarde|Omschrijving|
|------|-------------|
|VO-PRO	    |Praktijkonderwijs|
|VO-VMBO-BB	|Voorbereidend middelbaar beroepsonderwijs, basisberoepsgerichte leerweg|
|VO-VMBO-KB	|Voorbereidend middelbaar beroepsonderwijs, kaderberoepsgerichte leerweg|
|VO-VMBO-GL	|Voorbereidend middelbaar beroepsonderwijs, gemengde leerweg|
|VO-VMBO-TL	|Voorbereidend middelbaar beroepsonderwijs, theoretische leerweg|
|VO-HAVO	|    Hoger algemeen voortgezet onderwijs|
|VO-VWO	    |Voorbereidend wetenschappelijk onderwijs|
|VO-VBO	    |Overig voortgezet onderwijs Geldig tot 01-01-2018|

**Comment by edwinverwoerd** [comment]
Ga een check doen op de nu geldende lijst binnen de huidige uitwisselstandaarden wordt gebruikt.

**Comment by edwinverwoerd** [comment]
The vocabularies associated with the "Training Code" and "Course Code" data fields are defined in the following Document Code Lists t.b.v. EDEXML profile "FDE Set".https://www.edustandaard.nl/app/uploads/2020/09/Codelijsten-tbv-EDEXML-profiel-FDE-set_v20200401.xlsx

**Comment by edwinverwoerd** [comment]
SEM Tech Track 25-03-2022 lijstje zoals hierboven genoemd gaan we gebruiken.
