### ISSUE TITLE
Document Kennisnet-entree net role in ecosystem

### ISSUE THREAD

**Issue by mcginkel** [stichtingsem/ecosystem#56]

**Comment by niesink** [comment]
I've created #57 describing the role Entree plays in the sign-on proces. However I'm not quite sure this is sufficient or the right spot in the documentation to explain this dependency on Entree and how a user's ECK iD travels from SIS to LA during sign-on.

So I'm curious to hear other's thoughts on this.

**Comment by niesink** [comment]
PR was merged following approval of the updated documentation in the tech track meeting of February 25th.
