### ISSUE TITLE
Setup between the 4 services and the  relationship

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#6]
What protocol, authentication, and consent mechanism do we use to setup the relationship between a Market Place and the Learning Application?

Underlying questions to be answered are:

1. Which steps are involved in the setup protocol?
2. In what order?
3. How to authenticate parties and their roles?
4. Do we register the relationship in the central register (if we choose to use one)?

**Comment by mcginkel** [comment]
Isn't this more generic for all flows ? I would suggest to look at this one during Issue #5 . What is special for MP to LA relations?
