### ISSUE TITLE
Question: is it possible to have the same digideliveryid for 2 different schools?

### ISSUE THREAD

**Issue by mcginkel** [stichtingsem/ecosystem#66]
is it possible to have the same digideliveryid for 2 different schools?

**Comment by mcginkel** [comment]
when 2 schools use the same address, will the digideliveriid always be unique?

Maybe happening when 2 schools organize one course in one location

**Comment by hhaarsma** [comment]
Looks like we have an example of an special education school which acts both for primary and secundary education. PE and SE are in our system as different schools, but they have the same digideliveryid connected.

**Comment by hhaarsma** [comment]
And I see an example of 2 secundary schools (1 for Havo/VWO and 1 for Mavo) having the same addres and also indeed the same digideliveryid. (Eligant & Kompaan, Zutphen)

**Comment by edwinverwoerd** [comment]
Can you please send me the official registration to DUO (schoolname, address, brin_4 and brin_6). Just to check something.
Also the question what will be de value within the Entree Federation Authentication flow for each student. Do they have the same?

Beside this we also have to thing in two staps:
1)  School adminstration level and consent
2) Data on level:
-  Authenticatie
- Data sharing

**Comment by edwinverwoerd** [comment]
Can you please explain what is UWLR ID.  Because on this moment the digiDeliveryId is not yet a value in the current data-set. For this we roll-out the new UWLR 2.3 version..

**Comment by edwinverwoerd** [comment]
General this must not occur.  Based on the input I did a further analsye based on available chain data and my conclusion is that in this case there is a data / mapping error. See the pictures below.

![image](https://user-images.githubusercontent.com/66616707/160096392-2ecd5cb5-5c9d-426b-919f-7af71d8563b8.png)

**Comment by kvoer** [comment]
As discussed in the Technical Track the example was a data issue.
