### ISSUE TITLE
Is it possible to have 1 school with multiple DigideliveryIds?

### ISSUE THREAD

**Issue by hhaarsma** [stichtingsem/ecosystem#67]
Similar to #66 only the other way around.

Schools with multiple locations seem to have a challenge with setting up delivery locations and student locations  correctly.  It looks like this is sometimes solved by connecting multiple digideliveryids to 1 school.
If a student on that school then gets progress - should this be notified via all connected digideliveryids?

**Comment by edwinverwoerd** [comment]
Short answer is NO.

Within the ECO system around the identifier of the schoolId there is NO different between delivery location(s) and student location(s).  at least when we talk about the digiDeliveryId. The name may have been chosen somewhat unfortunately (if we look back in the process with the current chain)  But a digiDeliveryId says is whether the school location to which a student is administratively enrolled (see also #66).  This value is also given within the authentication flow (via the Entree Federation) as an authenticating value. The value is also used when designating a school (location) for which the learning materials are ordered and used. And the value also comes back within the exchange of SIS data etc. The digiDeliverryId register is managed by Edu-IX at the request of SEM and the various brache organisations.  The basis for determining the digiDeliveryId is the location data as registered at DUO. Value is determined on the basis of BRIN4 + Postal code + Full house number.

**Comment by kvoer** [comment]
As discussed in the Technical Track the example was a data issue.
