### ISSUE TITLE
Technical details in exchanging events

### ISSUE THREAD

**Issue by Jorimvdw** [stichtingsem/ecosystem#68]
Few issues are yet undecided (or undocumented):
- How often do we try to deliver an event?
   - Proposal: if you get a http 500 3 times, the sending party can stop for an hour to try to deliver the event?
- What if an event cannot be delivered. When a new event needs to be delivered, do we first try to deliver the old/failed event?
- Should we add http codes for example: overloaded? We can decide together what the sending party should do in case of certain http codes.
- What do we need to do when there are 2 changes for the same object/entity? Could it be possible that events are send out in the wrong order?

Other issues:
- What about the schemaversion in the object? Should we be backward compatible? How many versions?
- Why don't we use the common http statuscodes? Kees proposed a 0 for succes, why not just 200?

**Comment by mcginkel** [comment]
Initial thoughts

_- How often do we try to deliver an event?
 Proposal: if you get a http 500 3 times, the sending party can stop for an hour to try to deliver the event?_
  send again in 10 seconds, 20 seconds, 2 minutes, 10 minutes, 1 hour, 10 hours, 24 hours, 30 hours. STOP sending ?
 
_- What if an event cannot be delivered. When a new event needs to be delivered, do we first try to deliver the old/failed event?_
It is a stream, events are sequenced. so I would propose to deliver oldest first.
There should be no reason to fial an event other then technical (but then all events fail) or consent (so we can send events in another type, but not simular events)

_- Should we add http codes for example: overloaded? We can decide together what the sending party should do in case of certain http codes._
"The 503 status code indicates the server is busy, overloaded, or down for maintenance." In that case wait xx minutes and try again?

_- What do we need to do when there are 2 changes for the same object/entity? Could it be possible that events are send out in the wrong order?_
In case of catalog, course, and SIS events: As we send the latest state: we can skip the old onces if they are not delivered. In case of entitlement, usage and progress: thse should be in sequence, no skipping as they are always unique

_- What about the schemaversion in the object? Should we be backward compatible? How many versions?_
That is mainly there for the events, as we could version the GET endpoints. I would be backwards compatible for one version, for a period that we define the moment the versions change. So idea to have that a small amount of time, not for years.


- Why don't we use the common http statuscodes? Kees proposed a 0 for succes, why not just 200?
I suggested to make a difference between technical errors (infrastructure, servers not available or wrong configured, tornado's etc) and functional errors.
The technical errors use the http codes, the functional ones are part of the response or event data. 
A large argument not to use https status code: the errors can be so many that there are not suitable HTTP codes to map to. Secondly: when we go real events, the http code will always be 200 when the event is accepted, but the functional response code comes later in the confirmation event.

**Comment by edwinverwoerd** [comment]
Zijn veel punten bijelkaar. Issue is dus wat als een event niet verwerkt / opgepakt wordt.
Voor time-outs hebben we een error code om daarna te bepalen wat de bron moet doen. Nogmaals aanbieden x-keer?
Zelfde geldt voor andere technische issues. Nogmaals opnieuw aanbieden. Maar hoe vaak dan.

Wat doe je als source ingeval van niet afgeleverde event en er is een wijziging. Goede vraag: Volgens mij kan op basis van initiele datum/tijd gestuurd worden op wat moet er gebeuren.  Daarnaast ga ik er vanuit dat als een event binnenkomt met een informatie object die een wijzing bevat en deze is nog niet bij de SP dat er een melding komt toch. Of zit ik er nu naast.

Schemaverion hiervoor de open API definities volgen.

**Comment by kvoer** [comment]
Dit issue is met alle onderliggende vraagstukken voor de Events API en het versiebeheer besproken. We hebben de volgende voorstellen:

**Events API**
- Het Ecosysteem maakt gebruik van events zodat partijen berichten asynchroon kunnen verwerken. Hierbij is het de intentie dat alle events, indien deze correct zijn verstuurd, door de ontvangende partij worden geaccepteerd.
- Het niet accepteren van een bericht kan twee oorzaken hebben: a) de ontvanger ontvangt het bericht, maar kan deze om diverse redenen niet verder verwerken of b) de ontvangende partij is niet aanwezig om het bericht te ontvangen. Hier spreken we het volgende voor af.

a) De ontvanger ontvangt het bericht, maar kan deze om diverse redenen niet verwerken
We hanteren de volgende status codes voor de Events API:

| Status code | Status | StatusMessage | Toeliching |
|---|---|---|---|
| 200 | 0 | OK | Bericht succesvol ontvangen |
| 400 | 1 | Failing event | Bericht voldoet niet aan schemavalidatie |
| 400 | 2 | SchemaVersion not supported | De ontvanger kan de gehanteerde schemaVersion niet verwerken |
| 401 | 3 | Scope required | Verzender is niet geautoriseerd voor scope |
| 403 | 4 | Consent required | Geen tweezijdig consent geregistreerd voor Verzender en Ontvanger voor school |
| 403 | 5 | schoolIdentifier unknown | De verzender communiceert in de context van een school die niet bekend is bij de Ontvanger |
| 400 99 | Vullingsregel: in statusMessage een beschrijving van reden opnemen | Overige reden |
