### ISSUE TITLE
SchoolSubject.level cardinality

### ISSUE THREAD

**Issue by niesink** [stichtingsem/ecosystem#75]
During further analysis on mapping the Somtoday model to SchoolSubjects and levels we discovered two issues with the current idea of always requiring exactly one level.

These issues are:
* *Onderbouw*
It is quite common for schools to not specify or 'know' the level for a certain subject they offer, especially in the lower/early years of a study/programme. In these cases they often mark the level of the subject as 'onderbouw'. Depending on the school this might mean a combination of HAVO/VWO, a combination of VMBO-BB/KB or something else. As the school does not specify this level any more narrow than 'Onderbouw' it is impossible for the SIS to publish a specific level for this schoolsubject. One option would be to add 'Onderbouw' to the list of allowed values, but it might be nicer to just not specify a level at all in this case.
* *Combination levels*
In addition to the undefined 'Onderbouw' it is also quite common to offer a subject on a combination of two (or more) levels, VMBO-GL/TL is quite common, as are VMBO-KB/BB and HAVO/VWO. In this situation the classes/groups or students are not split into seperate levels, everybody takes the subject together for the same (combination) level. To accommodate this situation it seems best to include both levels with the SchoolSubject.

Therefor our suggestion would be to change the cardinality of SchoolSubject.level from (always) 1 to 0, 1 or more, i.e. change it from a required string to an optional array of strings.

**Comment by mcginkel** [comment]
Created new ticket for Koens comment. https://github.com/stichtingsem/ecosystem/issues/80
