### ISSUE TITLE
Share setup information between partners

### ISSUE THREAD

**Issue by hhaarsma** [stichtingsem/ecosystem#77]
As we approaching the moment again that we want to start exchanging information, it would be nice to share information regarding URLs and other inputs required to ocnfigure the systems.
Last year we used: https://github.com/stichtingsem/technology-prototype-private
Can we use this again?

I think that we need to share per partner:
- which API is supported, whether that is as consumer or provider, which URL should be used for it
- what is the URL for the authentication handshake, is there a specific Scope required?

and then per partner-partner connection, a ClientId and Secret should be made available 

Last year we put all the information (also the ClientIds/Secrets) in a file per partner.

**Comment by kvoer** [comment]
In the technical track meeting of 8th of April we decided:
- Endpoints will be added to the file SEM Party Directory.
- ClientIDs and secrets will be added by each party to the technology-prototype-private repository.
- Track Technical members have access to this repository.
