### ISSUE TITLE
new thoughts on schoolsubject fields and id's

### ISSUE THREAD

**Issue by mcginkel** [stichtingsem/ecosystem#80]
Koen Voermans:

In addition to [the comment of Luke](https://github.com/stichtingsem/ecosystem/issues/75) we discussed in the SIS meeting the following.

https://github.com/stichtingsem/ecosystem/issues/46 issue resulted in the need for a unique Identifier for the SchoolSubject. Above reasoning of Luke further shows the need for such a unique ID for a SchoolSubject.

If we implement this SchoolSubjectID we could remove all other data from other Information object with SchoolSubjects being the Entitlement and Student. This is a huge efficiency improvement when there is a change in descriptive data of a SchoolSubject (e.g. SchoolSubjectAbr changes from ak to ak1). In the current implementation this results into events for all Students that have the SchoolSubject and also the Entitlement of the variant SchoolSubject should change the descriptive value.

As a further consequence we should add a new Event from the SIS API where SchoolSubjects could be retrieved by the LMS and the LA. And events can be send whenever data changes according to the SchoolSubject. The consent flow should also be altered for exchange of information between SIS and LA, LMS, and MP for the SchoolSubjects.

Proposal

New get Endpoint in SIS API with SchoolSubject, get by ID

New event SchoolSubject in SIS API to communicate changes of values within a SchoolSubject, New SchoolSubject or Delete SchoolSubject

Replace the SchoolSubject Arrays in Entitlement and Student with an Array of SchoolSubjectIDs

Add SchoolSubject to Consent API for exchange of information from SIS to LA, MP, and LMS

**Comment by kvoer** [comment]
As a possible first step we could replace the SchoolSubjects in Entitlements by the SchoolSubjectId.

In case a field changes of SchoolSubject this change can be shared by the SIS API via the Students.

The MP is than not required to echo this change in all entitlements that have this changed SchoolSubject. And information keeps in sync and available from the source.

**Comment by kvoer** [comment]
Om dit issue af te sluiten hebben we nog de volgende keuzes te maken:

- Versturen van SchoolSubject in zijn geheel of als Id bij Student (en Teacher). Voorstel: ID
- Nieuw GET endpoint: GET SchoolSubject by ID. Voorstel: Ja
- Nieuw Event voor communiceren van wijzigingen in een SchoolSubject. Voorstel: Ja

**Comment by edwinverwoerd** [comment]
> Om dit issue af te sluiten hebben we nog de volgende keuzes te maken:
> 
> * Versturen van SchoolSubject in zijn geheel of als Id bij Student (en Teacher). Voorstel: ID
> * Nieuw GET endpoint: GET SchoolSubject by ID. Voorstel: Ja
> * Nieuw Event voor communiceren van nieuwe, verwijderde of wijzigingen in een SchoolSubject. Voorstel: Ja

> _AKKOORD_
