### ISSUE TITLE
Simple result Interface

### ISSUE THREAD

**Issue by mcginkel** [stichtingsem/ecosystem#81]
[20220331 - SimpleResult.pdf](https://github.com/stichtingsem/ecosystem/files/8425576/20220331.-.SimpleResult.pdf)

Er is een voorstel voor een simpele resultaat API.

**Comment by kvoer** [comment]
In de landelijke werkgroep is de berichtspecificatie in concept besproken. Hier is geen SchoolSubjectId in opgenomen. In de discussie hierover werd als argument aangevoerd:
- Het betreft een specifiek scenario waarbij de medewerker die het resultaat verstuurt, deze ook weer ontvangt in het resultaatverwerkende systeem.
- Deze medewerker is veelal een docent die in het resultaatverwerkende systeem alleen toegang heeft tot de cijferkolommen van specifieke vakken.
- Het SchoolSubjectId voegt in dit scenario niet veel toe om cijfers naar de juiste kolom te navigeren.

Om in lijn te blijven met de landelijke werkgroep, daarom het voorstel om SchoolSubjectId te verwijderen.
