### ISSUE TITLE
Entitlement - field Activation - required from rol MP is not okay

### ISSUE THREAD

**Issue by edwinverwoerd** [stichtingsem/ecosystem#85]
ActivationUntilDate string <date> required

Date - time ActivationUntil date, is the date on which the product can no longer be converted to a license. The agreement to activate the product has expired. This does not say anything about being able to use the product after activation before this date.

The question is: Is the MP the owner of this information or should this be the LA. The activationuntildate can be calculated by the LA based on the startdate.

And if the MP is the owner of this date the question is where can he find this information. The information in the catalogue is not complete enough.

Our suggestion is to let the LA calculate the date. Partly in view of possible new business models. Calculation based on the start date is then the starting point.

**Comment by kvoer** [comment]
For POC2 we will use a fixed date in the far future.

**Comment by kvoer** [comment]
In aanvulling op bovenstaand dilemma:
- De activatieperiode kan korter zijn dan de gebruiksperiode. Bijvoorbeeld je hebt 30 dagen de tijd om een product te activeren. Na activeren mag iedere gebruiker een jaar gebruiken (jaarlicentie).
- De expirationdate wordt door de LA gevuld in het InitialActivation event. Echter het LMS krijgt deze informatie niet standaard door. Hoe weet het LMS hoe lang de Link beschikbaar moet zijn voor de Leerling?

**Comment by kvoer** [comment]
Overwegingen:
- De activatieperiode heeft betrekking op het in gebruiken nemen van een leermiddel. Dit is onderdeel van het leverproces. De MP moet in staat zijn om deze informatie te delen met het LMS. In de Catalogue API zou hiervoor alle beschikbare informatie moeten zitten om de MP hiertoe in staat te stellen.
- De expirationDate wordt gevuld door de LA en kan in geval van abonnementen verschillen per gebruiker. Deze informatie kan de MP niet delen met het LMS. Dit heeft als gevolg dat het LMS in deze gevallen geabonneerd moet zijn op de Usage API van de LA om de duur van de licentie door te krijgen. Immers in deze unieke periode voor deze leerling moet de Link zichtbaar blijven.

Voorstel tot besluit:
- Opnemen object _activationPeriod_ in Catalogue API bestaande uit _activationVariant_ met ENUM (days, date, schoolperiod, schoolyear) en _activationValue_ gevuld met aantal dagen of specifieke datum. activationValue mag leeg blijven voor variant schoolyear. Hierbij geldt het gehele lopende schooljaar.
- Opnemen object _expirationVariant in Catalogue API bestaande uit ENUM (schoolyear, schoolperiod, variable). In de variant schoolyear blijft de link het gehele lopende schooljaar actief. In de variant schoolperiod voor de duur van de schoolperiode waarin de Leerling het product heeft geactiveerd. En in het geval van variable wordt de datum gecommuniceerd via de Usage API.

**Comment by kvoer** [comment]
Dit issue is in de werkgroep standaard van 9 november besproken. Hierbij zijn de volgende aanvullende argumenten genoemd:
- Het hanteren van schoolspecifieke schoolPeriods voor activatieperiodes kan tot veel verwarring leiden. In de praktijk blijkt dat aantal dagen, een ultieme datum en het lopende schooljaar werkbare varianten zijn.
- Luisteren naar de Usage API als LMS betekent dat de school hiervoor consent moet geven tussen LA en LMS. Dit is een extra drempel bij het inrichten van een Ecosysteem voor de school. Het is niet wenselijk dat als gevolg van het ontbreken van consent tussen LMS en LA voor Usage data een link niet geplaatst kan worden.
- De _activationUntilDate_ en de _expirationDate_ zijn van belang voor het LMS om goed beheer van links voor een leerling te doen. De link kan verwijderd worden voor producten die niet in gebruik zijn genomen door de leerling voor de activationUntilDate. En voor in gebruik genomen producten door de leerling geldt dat na de expirationDate de link ook verwijderd kan worden.

Het nieuwe wijzigingsvoorstel is:
- Opnemen object _activationPeriod_ in Product (Catalogue API) bestaande uit _activationVariant_ met ENUM (days, date, schoolperiod) en _activationValue_ gevuld met aantal dagen of specifieke datum. activationValue mag leeg blijven voor variant schoolyear. Hierbij geldt het gehele lopende schooljaar.
- Opnemen object _expirationVariant_ in Catalogue API bestaande uit ENUM (schoolyear, variable). In de variant schoolyear blijft de link het gehele lopende schooljaar actief.
- Zodra de _expirationVariant_ voor een entitled product _variable_ is dan wordt de link actief gehouden tot de _expirationDate_ voor de individuele leerling zoals gecommuniceerd door de LA via de Usage API. Hiervoor is consent noodzakelijk tussen LMS en LA.
- Indien er geen consent is geregistreerd tussen de LA en het LMS voor de Usage API dan blijft de link oneindig actief voor de Leerling en wordt er een melding gemaakt in de UI van het LMS dat er geen consent is geregistreerd tussen LMS en LA. Voor een LMS is het immers niet te bepalen of een product al dan niet in gebruik is genomen. Ook is de expirationDate onbekend.

**Comment by Jorimvdw** [comment]
Akkoord

**Comment by Eysbach** [comment]
> Overwegingen:
> 
> * De activatieperiode heeft betrekking op het in gebruiken nemen van een leermiddel. Dit is onderdeel van het leverproces. De MP moet in staat zijn om deze informatie te delen met het LMS. In de Catalogue API zou hiervoor alle beschikbare informatie moeten zitten om de MP hiertoe in staat te stellen. 
**RE: De activatieperiode kan variabel zijn met een (te berekenen) vaste einddatum (einde schooljaar). Of een vast aantal dagen vanaf de startdatum. Beide mogelijkheden moeten dan ondersteund worden.**

**Comment by Eysbach** [comment]
> Dit issue is in de werkgroep standaard van 9 november besproken. Hierbij zijn de volgende aanvullende argumenten genoemd:
> 
> * Het hanteren van schoolspecifieke schoolPeriods voor activatieperiodes kan tot veel verwarring leiden. In de praktijk blijkt dat aantal dagen, een ultieme datum en het lopende schooljaar werkbare varianten zijn.
**RE: Wij hebben een specifieke schoolPeriod (tot 15 juli)**

> * Luisteren naar de Usage API als LMS betekent dat de school hiervoor consent moet geven tussen LA en LMS. Dit is een extra drempel bij het inrichten van een Ecosysteem voor de school. Het is niet wenselijk dat als gevolg van het ontbreken van consent tussen LMS en LA voor Usage data een link niet geplaatst kan worden.
**RE: is inderdaad niet de juiste richting**

> * De _activationUntilDate_ en de _expirationDate_ zijn van belang voor het LMS om goed beheer van links voor een leerling te doen. De link kan verwijderd worden voor producten die door een leerling niet in gebruik zijn genomen voor de activationUntilDate. En voor door de leerling in gebruik genomen producten geldt dat na de expirationDate de link ook verwijderd kan worden.
**RE: Prima**

> * Het opnemen van een variabele _expirationVariant_ in het product van de Catalogue API lost het issue niet op. Het is immers nog steeds noodzakelijk om te weten of een product in gebruik is genomen door de leerling. Hiervoor blijft het noodzakelijk om naar de Usage API te luisteren naar InitialActivation berichten.
**>RE: Expirationdate dus meesturen met InitialActivation**

> Het nieuwe wijzigingsvoorstel is:
> 
> * Opnemen object _activationPeriod_ in Product (Catalogue API) bestaande uit _activationVariant_ met ENUM (days, date, schoolyear) en _activationDays_ gevuld met het aantal dagen voor de variant _days_ en _activationUntilDate_ met een vaste datum voor de variant _date_. De variant _schoolyear_ heeft als einddatum 31 juli van het lopende schooljaar.
**RE: ThiemeMeulenhoff hanteert 15 juli als einddatum van activationUntilDate? Dat is dus niet de expirationdate!**

> * Het LMS beheert de links voor een leerling conform de beschrijving hierboven. Indien het product niet tijdig in gebruik is genomen blijft de link actief tot de _activationUntilDate_. Indien het product wel in gebruik is genomen dan blijft de link actief tot de _expirationDate_. Hiervoor luistert het LMS naar de Usage API en in het bijzonder de InitialActivation berichten.
**RE: Mee eens**

> * Indien er geen consent is geregistreerd tussen de LA en het LMS voor de Usage API dan blijft de link oneindig actief **(RE: = “zichtbaar”)** voor de Leerling en wordt er een melding gemaakt in de UI van het LMS dat er geen consent is geregistreerd tussen LMS en LA. Voor een LMS is het immers niet te bepalen of een product al dan niet in gebruik is genomen. Ook is de _expirationDate_ onbekend. Dit kan ertoe leiden dat het klikken op een link leidt tot een melding bij de LA dat er geen toegang mogelijk is.
**RE: Het is wenselijk dat de link verdwijnt op de expirationDate en dat altijd bepaald kan worden door het LMS (ook als er geen consent is op de Usage API). Het is een statuskenmerk van een entitlement (expired).**

**RE: Een LMS moet de expiredate van een entitlement weten, ook zonder consent op de UsageAPI**

**Comment by kvoer** [comment]
De feedback is besproken in de werkgroep van 18 november.

Er is een nieuw voorstel ontwikkeld voor het versturen van een default experiationDate als onderdeel van de entitlement:
- We voegen een nieuw attribuut _minExpirationDate_ toe aan de entitlement. De MP berekent deze datum op basis van de productdefinitie uit de Catalogue API. Voor een digitaal product met een jaarlicentie is dit bijvoorbeeld 1 jaar na de startdatum van de activatieperiode.
- Het attribuut is optioneel en hoeft niet ingevuld te worden door de MP.
- Indien het attribuut leeg is dan wordt de link oneindig getoond door het LMS.
- Indien het attribuut gevuld is dan wordt de link tenminste tot de minExpirationDate klikbaar getoond.
- Indien het LMS van de LA via de Usage API in een InitialActivation bericht een expirationDate heeft ontvangen dan wordt dit de nieuwe datum tot wanneer de link klikbaar getoond wordt. Hierbij is de expirationDate altijd verder in de toekomst dan de minExpirationDate.

**Comment by linsegoeman** [comment]
akkoord vanuit Malmberg
