### ISSUE TITLE
createdAfter query parameter

### ISSUE THREAD

**Issue by Jorimvdw** [stichtingsem/ecosystem#89]
Volgens de specs kan je bij het ophalen van events een createdAfter query parameter meegeven om te filteren op events die gegenereerd zijn na tijdstip x. createdAfter is een number in de spec. Is dat seconden of milliseconden sinds 1970? (of een ander arbitrair tijdstip, zoals minuten sinds de troonsbestijging van Willem-Alexander)

**Comment by Jorimvdw** [comment]
unix epoch hebben we besloten

**Comment by kvoer** [comment]
Issue is solved, as discussed in the Technical Track of 29th of April
