### ISSUE TITLE
Support of local security standards

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#9]
How to  support locale (security) standards (example  data transmission used NL Edukoppeling for SaaS Vendor connections. Because of the Edu-K scope “afspraken stelsel, data convenant, Uniforme Beveiligingsvoorschriften, ….” )

**Comment by niesink** [comment]
Ter documentatie even twee linkjes: naar [de Edukoppeling standaard](https://www.edustandaard.nl/standaard_afspraken/edukoppeling-transactiestandaard/edukoppeling-februari-2021/) en specifiek [het REST profiel](https://www.edustandaard.nl/app/uploads/2021/02/2021-02-10-Edukoppeling-REST_SaaS-profiel-versie-1.0-definitief-1.pdf)

**Comment by kvoer** [comment]
We discuss with Edustandaard our priciples and its application to the requirements of Edukoppelingen.

**Comment by mcginkel** [comment]
When we use auth and client secrets this is the same 

SSL - We will use TLS protocol for encryption
We will not yet use client and server certificates that contain OIN numbers in this phase. It could be added later to become compliant with EDUKoppeling

The current protocol choices are secure.

**Comment by mcginkel** [comment]
For now (pilot 2) we will not implement edukoppeling. Based on the feedback we get from the review by edustandard we can open a new issue to improve/adjust.
