### ISSUE TITLE
Consent api questions

### ISSUE THREAD

**Issue by Jorimvdw** [stichtingsem/ecosystem#90]
The response of the request consent update has a producerReferenceId and a consumerReferenceId. Is the producer always the system where consent is first given? Or is producer the system that produces the response?

And I think that this endpoint should return a list of consents? https://stichtingsem.stoplight.io/docs/ecosystem/b3A6NDExNTI0MjU-get-consents-by-schoolid

**Comment by kvoer** [comment]
We discussed both questions in the Technical track of 22-4.
1. the producerReferenceId refers to the Producing party of the API and the consumerReferenceId to the consuming party of the API. For the SIS API, the producer is the SIS and the possible consumers are MP, LA, and LMS.
2. It is correct that the endpoint should be a list of consents.
