### ISSUE TITLE
Path parameter referenceId in Request Initial Sync

### ISSUE THREAD

**Issue by kvoer** [stichtingsem/ecosystem#91]
The Request Initial Sync endpoint requires a valid Token to be accessed. In order to receive this token the requesting party should have a valid consent. Therefore, the path parameter of referenceId in the Initial Sync endpoint is not required anymore.

This issue is discussed in the Technical Track meeting of 22-4. All members of the track agreed that the path parameter can be removed from the specification.

**Comment by mcginkel** [comment]
on 29-4 we discussed this again and added the reference id, as the LA can have multiple API's

Discussion is now if we can add the api name there. This combination is unique enough.
