### ISSUE TITLE
What should we fill in entitlementReceiveId?

### ISSUE THREAD

**Issue by Jorimvdw** [stichtingsem/ecosystem#94]
The responsebody off the AcceptEntitlement-POST endpoint contains a entitlementId and a entitlementReceiveId. What should we give back in the entitlementReceiveId?

**Comment by mcginkel** [comment]
entitlementReceiveId is the magic confirmation that the MP wanted as a unique reference for this action. I would create a new GUID for it)

**Comment by hhaarsma** [comment]
We also put a new Guid as a return value.

But should the EntitlementId be the ID that the LA generated for the entitlement, and then echo the Id of the entitlement from the request in the EntitlementReceiveId field (this is how I interpreted it)? Or the otherway around (this is what I read in the above remarks)?

**Comment by kvoer** [comment]
Issue is solved, as discussed in the Technical Track of 13th of May
