### ISSUE TITLE
After POC2: questions on implementing openapi yaml

### ISSUE THREAD

**Issue by mcginkel** [stichtingsem/ecosystem#96]
During the implementation one of our engineers added the following remarks on the openapi definition and code generation.
While the definitions are functionally correct, we could change a few things to make implementation easier:

_In line of my observations reg. the generated code we now have a list of following flaws that affect the specs itself - so depending on the future of the SEM project that would be something to look into:_

- _incomplete type reuse - there is inline types - or module (events, entitlement, etc.) private types (ideally common types would be moved to a central/shared yaml spec referenced by all other files requiring that type_

- _type inconsistencies: while e.g. EventData has an integer status - SimpleProgress on the other hand has String, Event#id is UUId while the response* id is String_

- _Inconsistent examples - where spec is not in line with the provided example, e.g. https://stichtingsem.stoplight.io/docs/ecosystem/c2NoOjM2MDU2ODc4-simple-progress_

- _Not_ sure if thats java generator specific, but it seems the generated code for the event handling does not map correctly to e.g. SimpleProgress - but falls back to EventData. Looking at the yaml files there is no discriminator defined that supports mapping the data part of the event to the “oneOf” listed types. Similar might apply to other places_

_IMHO it’s worth putting some effort into the specs before a handful parties implement it in the current state._
@mrechtien

**Comment by kvoer** [comment]
Voorstel tot besluit: consistent maken van de specificatie conform voorstellen.

**Comment by edwinverwoerd** [comment]
> Voorstel tot besluit: consistent maken van de specificatie conform voorstellen.

Akkoord hiermee kunnen we dus dit punt sluiten?
