### ISSUE TITLE
Catalogue API: Inconsistensies in Status values

### ISSUE THREAD

**Issue by hhaarsma** [stichtingsem/ecosystem#99]
On the Product itself a status can have values:
- not-yet-available
- limited-available
- available
- temporary-not-available
- no-longer-available
- will-never-be-available
- not-available-or-usable

On the Catalogue API for the GetProducts method a filter can be used on status, but there only 2 options are given:
- active
- not-for-sale

Shouldnt these options be in line with each other?

**Comment by kvoer** [comment]
Voorstel tot besluit: filter uitbreiden met alle statussen.

**Comment by edwinverwoerd** [comment]
> Voorstel tot besluit: filter uitbreiden met alle statussen.

_Niet mee eens, volgens mij gaat hier om iets anders dan alleen de status van beschikbaarheid van een product. Deze twee velden hebben als doel:

1.  welke producten zijn nog "actief" en dus ook welke is  "niet actief"
2. welke producten mogen door een derde partij verkocht worden

Doe is dat de catalogus volledig moet zijn. En dat we op basis van een extra kenmerk mogelijk ook oude data structureel netjes op te ruimen in het hele netwerk/keten _

**Comment by hhaarsma** [comment]
Dus dan krijg je met de active filter alle producten met status available of limited-availble en not-for-sale geeft de andere producten?
of gaat het om de statussen dat producten in de webshop getoond mogen worden en welke producten aangeboden kunnen worden aan gebruikers om mee te werken?

**Comment by kvoer** [comment]
In de werkgroep is het volgende besproken:

- De benaming not-for-sale heeft aanleiding gegeven om opnieuw na te denken over de definitie van een product.
- In de praktijk zijn er producten in de Catalogue die not-for-sale zijn. Bijvoorbeeld demoproducten. Hiervan wil je wel de informatie kunnen delen, moet een toegangslink beschikbaar zijn maar is het van belang dat iedereen weet dat ze niet te verwerven zijn.
- Voor dit doeleinde voegen we een nieuw attribuut toe aan het product: boolean forSale, default True en dus ook om te zetten naar False.
- Ten opzichte van de Distributie en Toegang status was het product al uitgebreid met een status not-available-or-usable. Dit betekent dat het product verwijderd en opgeruimd kan worden.

Voorstel tot besluit:
Toevoegen van attribuut forSale aan product in Catalogue API
In de Query Parameters wijzigen we:
- Status naar de volledige lijst met statussen
- forSale als extra parameter met True of False

**Comment by Jorimvdw** [comment]
Akkoord
